from collections import OrderedDict

#### VBF discriminator variables ####
vbf_discriminator_boosted_dnn_input_variables = OrderedDict(
    {
        "sequential": {
            # "vbf_jets_pt": ["JetGoodVBFCandidates", "pt", "log_norm"],
            # "vbf_jets_eta": ["JetGoodVBFCandidates", "eta", "norm"],
            # "vbf_jets_phi": ["JetGoodVBFCandidates", "phi", "norm"],
            # "vbf_jets_mass": ["JetGoodVBFCandidates", "mass", "norm"],
            "vbf_jets_pt": ["JetGoodVBF", "pt", "log_norm"],
            "vbf_jets_eta": ["JetGoodVBF", "eta", "norm"],
            "vbf_jets_phi": ["JetGoodVBF", "phi", "norm"],
            "vbf_jets_mass": ["JetGoodVBF", "mass", "norm"],
            },
        "global": {
            "HT": ["events", "HT", "log_norm"],
            "dijet_dEta": ["events", "dEta", "norm"],
            "higgs1_reco_pt": ["HiggsLeading", "pt", "log_norm"],
            "higgs1_reco_eta": ["HiggsLeading", "eta", "norm"],
            "higgs1_reco_phi": ["HiggsLeading", "phi", "norm"],
            "higgs1_reco_mass": ["HiggsLeading", "mass", "log_norm"],
            "higgs1_DeltaR_Hj": ["HiggsLeading", "dR_Hjet_min", "norm"],
            "higgs1_btagBB_wp": ["HiggsLeading", "btagBB_3wp", "norm"],
            "higgs1_centrality": ["HiggsLeading", "centrality", "norm"],
            "higgs1_mass_Hj": ["HiggsLeading", "m_Hjet_min_dR", "norm"],
            "higgs2_reco_pt": ["HiggsSubLeading", "pt", "log_norm"],
            "higgs2_reco_eta": ["HiggsSubLeading", "eta", "norm"],
            "higgs2_reco_phi": ["HiggsSubLeading", "phi", "norm"],
            "higgs2_reco_mass": ["HiggsSubLeading", "mass", "log_norm"],
            "higgs2_DeltaR_Hj": ["HiggsSubLeading", "dR_Hjet_min", "norm"],
            "higgs2_btagBB_wp": ["HiggsSubLeading", "btagBB_3wp", "norm"],
            "higgs2_centrality": ["HiggsSubLeading", "centrality", "norm"],
            "higgs2_mass_Hj": ["HiggsSubLeading", "m_Hjet_min_dR", "norm"],
            "hh_vec_pt": ["HH", "pt", "log_norm"],
            "hh_vec_eta": ["HH", "eta", "norm"],
            "hh_vec_phi": ["HH", "phi", "norm"],
            "hh_vec_mass": ["HH", "mass", "log_norm"],
            "hh_vec_DeltaR": ["HH", "dR", "norm"],
            "hh_vec_DeltaEta": ["HH", "dEta", "norm"],
            "hh_vec_DeltaPhi": ["HH", "dPhi", "norm"],
            "hh_CosThetaStar_CS": ["HH", "Costhetastar_CS", "norm"],
            "dijet_LeadingJet_pt": ["LeadingVBFJet", "pt", "log_norm"],
            "dijet_LeadingJet_eta": ["LeadingVBFJet", "eta", "norm"],
            "dijet_LeadingJet_phi": ["LeadingVBFJet", "phi", "norm"],
            "dijet_LeadingJet_mass": ["LeadingVBFJet", "mass", "log_norm"],
            "dijet_SubLeadingJet_pt": ["SubLeadingVBFJet", "pt", "log_norm"],
            "dijet_SubLeadingJet_eta": ["SubLeadingVBFJet", "eta", "norm"],
            "dijet_SubLeadingJet_phi": ["SubLeadingVBFJet", "phi", "norm"],
            "dijet_SubLeadingJet_mass": ["SubLeadingVBFJet", "mass", "log_norm"],
            "met_et": ["PuppiMET", "sumEt", "norm"],
            },
    }
)
vbf_discriminator_boosted_dnn_input_variables_test = OrderedDict(
    {
        "sequential": {
            "vbf_jets_pt": ["JetGoodVBF", "pt", "log_norm"],
            "vbf_jets_eta": ["JetGoodVBF", "eta", "norm"],
            "vbf_jets_phi": ["JetGoodVBF", "phi", "norm"],
            "vbf_jets_mass": ["JetGoodVBF", "mass", "norm"],
            },
        "global": {
            "HT": ["events", "HT", "log_norm"],
            "higgs1_reco_pt": ["HiggsLeading", "pt", "log_norm"],
            "higgs1_reco_eta": ["HiggsLeading", "eta", "norm"],
            "higgs1_reco_phi": ["HiggsLeading", "phi", "norm"],
            "higgs1_reco_mass": ["HiggsLeading", "mass", "log_norm"],
            "higgs1_DeltaR_Hj": ["HiggsLeading", "dR_Hjet_min", "norm"],
            "higgs1_btagBB_wp": ["HiggsLeading", "btagBB_3wp", "norm"],
            "higgs1_centrality": ["HiggsLeading", "centrality", "norm"],
            "higgs1_mass_Hj": ["HiggsLeading", "m_Hjet_min_dR", "norm"],
            "higgs2_reco_pt": ["HiggsSubLeading", "pt", "log_norm"],
            "higgs2_reco_eta": ["HiggsSubLeading", "eta", "norm"],
            "higgs2_reco_phi": ["HiggsSubLeading", "phi", "norm"],
            "higgs2_reco_mass": ["HiggsSubLeading", "mass", "log_norm"],
            "higgs2_DeltaR_Hj": ["HiggsSubLeading", "dR_Hjet_min", "norm"],
            "higgs2_btagBB_wp": ["HiggsSubLeading", "btagBB_3wp", "norm"],
            "higgs2_centrality": ["HiggsSubLeading", "centrality", "norm"],
            "higgs2_mass_Hj": ["HiggsSubLeading", "m_Hjet_min_dR", "norm"],
            "hh_vec_pt": ["HH", "pt", "log_norm"],
            "hh_vec_eta": ["HH", "eta", "norm"],
            # "hh_vec_phi": ["HH", "phi", "norm"],
            "hh_vec_mass": ["HH", "mass", "log_norm"],
            "hh_vec_DeltaR": ["HH", "dR", "norm"],
            "hh_vec_DeltaEta": ["HH", "dEta", "norm"],
            "hh_vec_DeltaPhi": ["HH", "dPhi", "norm"],
            "hh_CosThetaStar_CS": ["HH", "Costhetastar_CS", "norm"],
            "dijet_LeadingJet_pt": ["LeadingVBFJet", "pt", "log_norm"],
            "dijet_LeadingJet_eta": ["LeadingVBFJet", "eta", "norm"],
            "dijet_LeadingJet_phi": ["LeadingVBFJet", "phi", "norm"],
            "dijet_LeadingJet_mass": ["LeadingVBFJet", "mass", "log_norm"],
            "dijet_SubLeadingJet_pt": ["SubLeadingVBFJet", "pt", "log_norm"],
            "dijet_SubLeadingJet_eta": ["SubLeadingVBFJet", "eta", "norm"],
            "dijet_SubLeadingJet_phi": ["SubLeadingVBFJet", "phi", "norm"],
            "dijet_SubLeadingJet_mass": ["SubLeadingVBFJet", "mass", "log_norm"],
            "met_et": ["PuppiMET", "sumEt", "norm"],
            },
    }
)

#### Background Morphing Variables ####

bkg_morphing_dnn_input_variables = OrderedDict(
    {
        "era": ["events", "era"],
        "higgs1_reco_pt": ["HiggsLeading", "pt"],
        "higgs1_reco_eta": ["HiggsLeading", "eta"],
        "higgs1_reco_phi": ["HiggsLeading", "phi"],
        "higgs1_reco_mass": ["HiggsLeading", "mass"],
        "higgs2_reco_pt": ["HiggsSubLeading", "pt"],
        "higgs2_reco_eta": ["HiggsSubLeading", "eta"],
        "higgs2_reco_phi": ["HiggsSubLeading", "phi"],
        "higgs2_reco_mass": ["HiggsSubLeading", "mass"],
        "HT": ["events", "HT"],
        "higgs1_DeltaRjj": ["HiggsLeading", "dR"],
        "higgs2_DeltaRjj": ["HiggsSubLeading", "dR"],
        "minDeltaR_Higgjj": ["events", "dR_min"],
        "maxDeltaR_Higgjj": ["events", "dR_max"],
        "higgs1_helicityCosTheta": ["HiggsLeading", "helicityCosTheta"],
        "higgs2_helicityCosTheta": ["HiggsSubLeading", "helicityCosTheta"],
        "hh_CosThetaStar_CS": ["HH", "Costhetastar_CS"],
        "hh_vec_mass": ["HH", "mass"],
        "hh_vec_pt": ["HH", "pt"],
        "hh_vec_eta": ["HH", "eta"],
        "hh_vec_DeltaR": ["HH", "dR"],
        "hh_vec_DeltaPhi": ["HH", "dPhi"],
        "hh_vec_DeltaEta": ["HH", "dEta"],
        "higgs1_reco_jet1_pt": ["JetGoodFromHiggsOrdered:0", "pt"],
        "higgs1_reco_jet1_eta": ["JetGoodFromHiggsOrdered:0", "eta"],
        "higgs1_reco_jet1_phi": ["JetGoodFromHiggsOrdered:0", "phi"],
        "higgs1_reco_jet1_mass": ["JetGoodFromHiggsOrdered:0", "mass"],
        "higgs1_reco_jet2_pt": ["JetGoodFromHiggsOrdered:1", "pt"],
        "higgs1_reco_jet2_eta": ["JetGoodFromHiggsOrdered:1", "eta"],
        "higgs1_reco_jet2_phi": ["JetGoodFromHiggsOrdered:1", "phi"],
        "higgs1_reco_jet2_mass": ["JetGoodFromHiggsOrdered:1", "mass"],
        "higgs2_reco_jet1_pt": ["JetGoodFromHiggsOrdered:2", "pt"],
        "higgs2_reco_jet1_eta": ["JetGoodFromHiggsOrdered:2", "eta"],
        "higgs2_reco_jet1_phi": ["JetGoodFromHiggsOrdered:2", "phi"],
        "higgs2_reco_jet1_mass": ["JetGoodFromHiggsOrdered:2", "mass"],
        "higgs2_reco_jet2_pt": ["JetGoodFromHiggsOrdered:3", "pt"],
        "higgs2_reco_jet2_eta": ["JetGoodFromHiggsOrdered:3", "eta"],
        "higgs2_reco_jet2_phi": ["JetGoodFromHiggsOrdered:3", "phi"],
        "higgs2_reco_jet2_mass": ["JetGoodFromHiggsOrdered:3", "mass"],
        "add_jet1pt_pt": ["add_jet1pt", "pt"],
        "add_jet1pt_eta": ["add_jet1pt", "eta"],
        "add_jet1pt_phi": ["add_jet1pt", "phi"],
        "add_jet1pt_mass": ["add_jet1pt", "mass"],
        "sigma_over_higgs1_reco_mass": ["events", "sigma_over_higgs1_reco_mass"],
        "sigma_over_higgs2_reco_mass": ["events", "sigma_over_higgs2_reco_mass"],
    }
)

bkg_morphing_dnn_DeltaProb_input_variables = OrderedDict(
    {
        "era": ["events", "era"],
        "Delta_pairing_probabilities": ["events", "Delta_pairing_probabilities"],
        "higgs1_reco_pt": ["HiggsLeading", "pt"],
        "higgs1_reco_eta": ["HiggsLeading", "eta"],
        "higgs1_reco_phi": ["HiggsLeading", "phi"],
        "higgs1_reco_mass": ["HiggsLeading", "mass"],
        "higgs2_reco_pt": ["HiggsSubLeading", "pt"],
        "higgs2_reco_eta": ["HiggsSubLeading", "eta"],
        "higgs2_reco_phi": ["HiggsSubLeading", "phi"],
        "higgs2_reco_mass": ["HiggsSubLeading", "mass"],
        "HT": ["events", "HT"],
        "higgs1_DeltaRjj": ["HiggsLeading", "dR"],
        "higgs2_DeltaRjj": ["HiggsSubLeading", "dR"],
        "minDeltaR_Higgjj": ["events", "dR_min"],
        "maxDeltaR_Higgjj": ["events", "dR_max"],
        "higgs1_helicityCosTheta": ["HiggsLeading", "helicityCosTheta"],
        "higgs2_helicityCosTheta": ["HiggsSubLeading", "helicityCosTheta"],
        "hh_CosThetaStar_CS": ["HH", "Costhetastar_CS"],
        "hh_vec_mass": ["HH", "mass"],
        "hh_vec_pt": ["HH", "pt"],
        "hh_vec_eta": ["HH", "eta"],
        "hh_vec_DeltaR": ["HH", "dR"],
        "hh_vec_DeltaPhi": ["HH", "dPhi"],
        "hh_vec_DeltaEta": ["HH", "dEta"],
        "higgs1_reco_jet1_pt": ["JetGoodFromHiggsOrdered:0", "pt"],
        "higgs1_reco_jet1_eta": ["JetGoodFromHiggsOrdered:0", "eta"],
        "higgs1_reco_jet1_phi": ["JetGoodFromHiggsOrdered:0", "phi"],
        "higgs1_reco_jet1_mass": ["JetGoodFromHiggsOrdered:0", "mass"],
        "higgs1_reco_jet2_pt": ["JetGoodFromHiggsOrdered:1", "pt"],
        "higgs1_reco_jet2_eta": ["JetGoodFromHiggsOrdered:1", "eta"],
        "higgs1_reco_jet2_phi": ["JetGoodFromHiggsOrdered:1", "phi"],
        "higgs1_reco_jet2_mass": ["JetGoodFromHiggsOrdered:1", "mass"],
        "higgs2_reco_jet1_pt": ["JetGoodFromHiggsOrdered:2", "pt"],
        "higgs2_reco_jet1_eta": ["JetGoodFromHiggsOrdered:2", "eta"],
        "higgs2_reco_jet1_phi": ["JetGoodFromHiggsOrdered:2", "phi"],
        "higgs2_reco_jet1_mass": ["JetGoodFromHiggsOrdered:2", "mass"],
        "higgs2_reco_jet2_pt": ["JetGoodFromHiggsOrdered:3", "pt"],
        "higgs2_reco_jet2_eta": ["JetGoodFromHiggsOrdered:3", "eta"],
        "higgs2_reco_jet2_phi": ["JetGoodFromHiggsOrdered:3", "phi"],
        "higgs2_reco_jet2_mass": ["JetGoodFromHiggsOrdered:3", "mass"],
        "add_jet1pt_pt": ["add_jet1pt", "pt"],
        "add_jet1pt_eta": ["add_jet1pt", "eta"],
        "add_jet1pt_phi": ["add_jet1pt", "phi"],
        "add_jet1pt_mass": ["add_jet1pt", "mass"],
        "sigma_over_higgs1_reco_mass": ["events", "sigma_over_higgs1_reco_mass"],
        "sigma_over_higgs2_reco_mass": ["events", "sigma_over_higgs2_reco_mass"],
    }
)

bkg_morphing_dnn_ArctanhDeltaProb_input_variables = OrderedDict(
    {
        "era": ["events", "era"],
        "Arctanh_Delta_pairing_probabilities": [
            "events",
            "Arctanh_Delta_pairing_probabilities",
        ],
        "higgs1_reco_pt": ["HiggsLeading", "pt"],
        "higgs1_reco_eta": ["HiggsLeading", "eta"],
        "higgs1_reco_phi": ["HiggsLeading", "phi"],
        "higgs1_reco_mass": ["HiggsLeading", "mass"],
        "higgs2_reco_pt": ["HiggsSubLeading", "pt"],
        "higgs2_reco_eta": ["HiggsSubLeading", "eta"],
        "higgs2_reco_phi": ["HiggsSubLeading", "phi"],
        "higgs2_reco_mass": ["HiggsSubLeading", "mass"],
        "HT": ["events", "HT"],
        "higgs1_DeltaRjj": ["HiggsLeading", "dR"],
        "higgs2_DeltaRjj": ["HiggsSubLeading", "dR"],
        "minDeltaR_Higgjj": ["events", "dR_min"],
        "maxDeltaR_Higgjj": ["events", "dR_max"],
        "higgs1_helicityCosTheta": ["HiggsLeading", "helicityCosTheta"],
        "higgs2_helicityCosTheta": ["HiggsSubLeading", "helicityCosTheta"],
        "hh_CosThetaStar_CS": ["HH", "Costhetastar_CS"],
        "hh_vec_mass": ["HH", "mass"],
        "hh_vec_pt": ["HH", "pt"],
        "hh_vec_eta": ["HH", "eta"],
        "hh_vec_DeltaR": ["HH", "dR"],
        "hh_vec_DeltaPhi": ["HH", "dPhi"],
        "hh_vec_DeltaEta": ["HH", "dEta"],
        "higgs1_reco_jet1_pt": ["JetGoodFromHiggsOrdered:0", "pt"],
        "higgs1_reco_jet1_eta": ["JetGoodFromHiggsOrdered:0", "eta"],
        "higgs1_reco_jet1_phi": ["JetGoodFromHiggsOrdered:0", "phi"],
        "higgs1_reco_jet1_mass": ["JetGoodFromHiggsOrdered:0", "mass"],
        "higgs1_reco_jet2_pt": ["JetGoodFromHiggsOrdered:1", "pt"],
        "higgs1_reco_jet2_eta": ["JetGoodFromHiggsOrdered:1", "eta"],
        "higgs1_reco_jet2_phi": ["JetGoodFromHiggsOrdered:1", "phi"],
        "higgs1_reco_jet2_mass": ["JetGoodFromHiggsOrdered:1", "mass"],
        "higgs2_reco_jet1_pt": ["JetGoodFromHiggsOrdered:2", "pt"],
        "higgs2_reco_jet1_eta": ["JetGoodFromHiggsOrdered:2", "eta"],
        "higgs2_reco_jet1_phi": ["JetGoodFromHiggsOrdered:2", "phi"],
        "higgs2_reco_jet1_mass": ["JetGoodFromHiggsOrdered:2", "mass"],
        "higgs2_reco_jet2_pt": ["JetGoodFromHiggsOrdered:3", "pt"],
        "higgs2_reco_jet2_eta": ["JetGoodFromHiggsOrdered:3", "eta"],
        "higgs2_reco_jet2_phi": ["JetGoodFromHiggsOrdered:3", "phi"],
        "higgs2_reco_jet2_mass": ["JetGoodFromHiggsOrdered:3", "mass"],
        "add_jet1pt_pt": ["add_jet1pt", "pt"],
        "add_jet1pt_eta": ["add_jet1pt", "eta"],
        "add_jet1pt_phi": ["add_jet1pt", "phi"],
        "add_jet1pt_mass": ["add_jet1pt", "mass"],
        "sigma_over_higgs1_reco_mass": ["events", "sigma_over_higgs1_reco_mass"],
        "sigma_over_higgs2_reco_mass": ["events", "sigma_over_higgs2_reco_mass"],
    }
)

bkg_morphing_dnn_BinnedArctanhDeltaProb_input_variables = OrderedDict(
    {
        "era": ["events", "era"],
        "Binned_Arctanh_Delta_pairing_probabilities": [
            "events",
            "Binned_Arctanh_Delta_pairing_probabilities",
        ],
        "higgs1_reco_pt": ["HiggsLeading", "pt"],
        "higgs1_reco_eta": ["HiggsLeading", "eta"],
        "higgs1_reco_phi": ["HiggsLeading", "phi"],
        "higgs1_reco_mass": ["HiggsLeading", "mass"],
        "higgs2_reco_pt": ["HiggsSubLeading", "pt"],
        "higgs2_reco_eta": ["HiggsSubLeading", "eta"],
        "higgs2_reco_phi": ["HiggsSubLeading", "phi"],
        "higgs2_reco_mass": ["HiggsSubLeading", "mass"],
        "HT": ["events", "HT"],
        "higgs1_DeltaRjj": ["HiggsLeading", "dR"],
        "higgs2_DeltaRjj": ["HiggsSubLeading", "dR"],
        "minDeltaR_Higgjj": ["events", "dR_min"],
        "maxDeltaR_Higgjj": ["events", "dR_max"],
        "higgs1_helicityCosTheta": ["HiggsLeading", "helicityCosTheta"],
        "higgs2_helicityCosTheta": ["HiggsSubLeading", "helicityCosTheta"],
        "hh_CosThetaStar_CS": ["HH", "Costhetastar_CS"],
        "hh_vec_mass": ["HH", "mass"],
        "hh_vec_pt": ["HH", "pt"],
        "hh_vec_eta": ["HH", "eta"],
        "hh_vec_DeltaR": ["HH", "dR"],
        "hh_vec_DeltaPhi": ["HH", "dPhi"],
        "hh_vec_DeltaEta": ["HH", "dEta"],
        "higgs1_reco_jet1_pt": ["JetGoodFromHiggsOrdered:0", "pt"],
        "higgs1_reco_jet1_eta": ["JetGoodFromHiggsOrdered:0", "eta"],
        "higgs1_reco_jet1_phi": ["JetGoodFromHiggsOrdered:0", "phi"],
        "higgs1_reco_jet1_mass": ["JetGoodFromHiggsOrdered:0", "mass"],
        "higgs1_reco_jet2_pt": ["JetGoodFromHiggsOrdered:1", "pt"],
        "higgs1_reco_jet2_eta": ["JetGoodFromHiggsOrdered:1", "eta"],
        "higgs1_reco_jet2_phi": ["JetGoodFromHiggsOrdered:1", "phi"],
        "higgs1_reco_jet2_mass": ["JetGoodFromHiggsOrdered:1", "mass"],
        "higgs2_reco_jet1_pt": ["JetGoodFromHiggsOrdered:2", "pt"],
        "higgs2_reco_jet1_eta": ["JetGoodFromHiggsOrdered:2", "eta"],
        "higgs2_reco_jet1_phi": ["JetGoodFromHiggsOrdered:2", "phi"],
        "higgs2_reco_jet1_mass": ["JetGoodFromHiggsOrdered:2", "mass"],
        "higgs2_reco_jet2_pt": ["JetGoodFromHiggsOrdered:3", "pt"],
        "higgs2_reco_jet2_eta": ["JetGoodFromHiggsOrdered:3", "eta"],
        "higgs2_reco_jet2_phi": ["JetGoodFromHiggsOrdered:3", "phi"],
        "higgs2_reco_jet2_mass": ["JetGoodFromHiggsOrdered:3", "mass"],
        "add_jet1pt_pt": ["add_jet1pt", "pt"],
        "add_jet1pt_eta": ["add_jet1pt", "eta"],
        "add_jet1pt_phi": ["add_jet1pt", "phi"],
        "add_jet1pt_mass": ["add_jet1pt", "mass"],
        "sigma_over_higgs1_reco_mass": ["events", "sigma_over_higgs1_reco_mass"],
        "sigma_over_higgs2_reco_mass": ["events", "sigma_over_higgs2_reco_mass"],
    }
)

bkg_morphing_dnn_PaddedArctanhDeltaProb_input_variables = OrderedDict(
    {
        "era": ["events", "era"],
        "Padded_Arctanh_Delta_pairing_probabilities": [
            "events",
            "Padded_Arctanh_Delta_pairing_probabilities",
        ],
        "higgs1_reco_pt": ["HiggsLeading", "pt"],
        "higgs1_reco_eta": ["HiggsLeading", "eta"],
        "higgs1_reco_phi": ["HiggsLeading", "phi"],
        "higgs1_reco_mass": ["HiggsLeading", "mass"],
        "higgs2_reco_pt": ["HiggsSubLeading", "pt"],
        "higgs2_reco_eta": ["HiggsSubLeading", "eta"],
        "higgs2_reco_phi": ["HiggsSubLeading", "phi"],
        "higgs2_reco_mass": ["HiggsSubLeading", "mass"],
        "HT": ["events", "HT"],
        "higgs1_DeltaRjj": ["HiggsLeading", "dR"],
        "higgs2_DeltaRjj": ["HiggsSubLeading", "dR"],
        "minDeltaR_Higgjj": ["events", "dR_min"],
        "maxDeltaR_Higgjj": ["events", "dR_max"],
        "higgs1_helicityCosTheta": ["HiggsLeading", "helicityCosTheta"],
        "higgs2_helicityCosTheta": ["HiggsSubLeading", "helicityCosTheta"],
        "hh_CosThetaStar_CS": ["HH", "Costhetastar_CS"],
        "hh_vec_mass": ["HH", "mass"],
        "hh_vec_pt": ["HH", "pt"],
        "hh_vec_eta": ["HH", "eta"],
        "hh_vec_DeltaR": ["HH", "dR"],
        "hh_vec_DeltaPhi": ["HH", "dPhi"],
        "hh_vec_DeltaEta": ["HH", "dEta"],
        "higgs1_reco_jet1_pt": ["JetGoodFromHiggsOrdered:0", "pt"],
        "higgs1_reco_jet1_eta": ["JetGoodFromHiggsOrdered:0", "eta"],
        "higgs1_reco_jet1_phi": ["JetGoodFromHiggsOrdered:0", "phi"],
        "higgs1_reco_jet1_mass": ["JetGoodFromHiggsOrdered:0", "mass"],
        "higgs1_reco_jet2_pt": ["JetGoodFromHiggsOrdered:1", "pt"],
        "higgs1_reco_jet2_eta": ["JetGoodFromHiggsOrdered:1", "eta"],
        "higgs1_reco_jet2_phi": ["JetGoodFromHiggsOrdered:1", "phi"],
        "higgs1_reco_jet2_mass": ["JetGoodFromHiggsOrdered:1", "mass"],
        "higgs2_reco_jet1_pt": ["JetGoodFromHiggsOrdered:2", "pt"],
        "higgs2_reco_jet1_eta": ["JetGoodFromHiggsOrdered:2", "eta"],
        "higgs2_reco_jet1_phi": ["JetGoodFromHiggsOrdered:2", "phi"],
        "higgs2_reco_jet1_mass": ["JetGoodFromHiggsOrdered:2", "mass"],
        "higgs2_reco_jet2_pt": ["JetGoodFromHiggsOrdered:3", "pt"],
        "higgs2_reco_jet2_eta": ["JetGoodFromHiggsOrdered:3", "eta"],
        "higgs2_reco_jet2_phi": ["JetGoodFromHiggsOrdered:3", "phi"],
        "higgs2_reco_jet2_mass": ["JetGoodFromHiggsOrdered:3", "mass"],
        "add_jet1pt_pt": ["add_jet1pt", "pt"],
        "add_jet1pt_eta": ["add_jet1pt", "eta"],
        "add_jet1pt_phi": ["add_jet1pt", "phi"],
        "add_jet1pt_mass": ["add_jet1pt", "mass"],
        "sigma_over_higgs1_reco_mass": ["events", "sigma_over_higgs1_reco_mass"],
        "sigma_over_higgs2_reco_mass": ["events", "sigma_over_higgs2_reco_mass"],
    }
)

bkg_morphing_dnn_input_variables_altOrder = OrderedDict(
    {
        "era": ["events", "era"],
        "higgs1_reco_pt": ["HiggsLeading", "pt"],
        "higgs1_reco_eta": ["HiggsLeading", "eta"],
        "higgs1_reco_phi": ["HiggsLeading", "phi"],
        "higgs1_reco_mass": ["HiggsLeading", "mass"],
        "higgs2_reco_pt": ["HiggsSubLeading", "pt"],
        "higgs2_reco_eta": ["HiggsSubLeading", "eta"],
        "higgs2_reco_phi": ["HiggsSubLeading", "phi"],
        "higgs2_reco_mass": ["HiggsSubLeading", "mass"],
        "HT": ["events", "HT"],
        "higgs1_DeltaRjj": ["HiggsLeading", "dR"],
        "higgs2_DeltaRjj": ["HiggsSubLeading", "dR"],
        "minDeltaR_Higgjj": ["events", "dR_min"],
        "maxDeltaR_Higgjj": ["events", "dR_max"],
        "higgs1_helicityCosTheta": ["HiggsLeading", "helicityCosTheta"],
        "higgs2_helicityCosTheta": ["HiggsSubLeading", "helicityCosTheta"],
        "hh_CosThetaStar_CS": ["HH", "Costhetastar_CS"],
        "hh_vec_mass": ["HH", "mass"],
        "hh_vec_pt": ["HH", "pt"],
        "hh_vec_eta": ["HH", "eta"],
        "hh_vec_DeltaR": ["HH", "dR"],
        "hh_vec_DeltaPhi": ["HH", "dPhi"],
        "hh_vec_DeltaEta": ["HH", "dEta"],
        "higgs1_reco_jet1_pt": ["JetGoodFromHiggsOrdered:0", "pt"],
        "higgs1_reco_jet2_pt": ["JetGoodFromHiggsOrdered:1", "pt"],
        "higgs2_reco_jet1_pt": ["JetGoodFromHiggsOrdered:2", "pt"],
        "higgs2_reco_jet2_pt": ["JetGoodFromHiggsOrdered:3", "pt"],
        "higgs1_reco_jet1_eta": ["JetGoodFromHiggsOrdered:0", "eta"],
        "higgs1_reco_jet2_eta": ["JetGoodFromHiggsOrdered:1", "eta"],
        "higgs2_reco_jet1_eta": ["JetGoodFromHiggsOrdered:2", "eta"],
        "higgs2_reco_jet2_eta": ["JetGoodFromHiggsOrdered:3", "eta"],
        "higgs1_reco_jet1_phi": ["JetGoodFromHiggsOrdered:0", "phi"],
        "higgs1_reco_jet2_phi": ["JetGoodFromHiggsOrdered:1", "phi"],
        "higgs2_reco_jet1_phi": ["JetGoodFromHiggsOrdered:2", "phi"],
        "higgs2_reco_jet2_phi": ["JetGoodFromHiggsOrdered:3", "phi"],
        "higgs1_reco_jet1_mass": ["JetGoodFromHiggsOrdered:0", "mass"],
        "higgs1_reco_jet2_mass": ["JetGoodFromHiggsOrdered:1", "mass"],
        "higgs2_reco_jet1_mass": ["JetGoodFromHiggsOrdered:2", "mass"],
        "higgs2_reco_jet2_mass": ["JetGoodFromHiggsOrdered:3", "mass"],
        "add_jet1pt_pt": ["add_jet1pt", "pt"],
        "add_jet1pt_eta": ["add_jet1pt", "eta"],
        "add_jet1pt_phi": ["add_jet1pt", "phi"],
        "add_jet1pt_mass": ["add_jet1pt", "mass"],
        "sigma_over_higgs1_reco_mass": ["events", "sigma_over_higgs1_reco_mass"],
        "sigma_over_higgs2_reco_mass": ["events", "sigma_over_higgs2_reco_mass"],
    }
)


bkg_morphing_dnn_SigBkgVariables_input_variables = OrderedDict(
    {
        "era": ["events", "era"],
        "HT": ["events", "HT"],
        "hh_vec_mass": ["HH", "mass"],
        "hh_vec_pt": ["HH", "pt"],
        "hh_vec_eta": ["HH", "eta"],
        "hh_vec_phi": ["HH", "phi"],
        "hh_vec_DeltaPhi": ["HH", "dPhi"],
        "hh_vec_DeltaEta": ["HH", "dEta"],
        "hh_vec_DeltaR": ["HH", "dR"],
        "hh_CosThetaStar_CS": ["HH", "Costhetastar_CS"],
        "higgs1_reco_pt": ["HiggsLeading", "pt"],
        "higgs1_reco_eta": ["HiggsLeading", "eta"],
        "higgs1_reco_phi": ["HiggsLeading", "phi"],
        "higgs1_reco_mass": ["HiggsLeading", "mass"],
        "higgs2_reco_pt": ["HiggsSubLeading", "pt"],
        "higgs2_reco_eta": ["HiggsSubLeading", "eta"],
        "higgs2_reco_phi": ["HiggsSubLeading", "phi"],
        "higgs2_reco_mass": ["HiggsSubLeading", "mass"],
        "higgs1_DeltaPhijj": ["HiggsLeading", "dPhi"],
        "higgs2_DeltaPhijj": ["HiggsSubLeading", "dPhi"],
        "higgs1_DeltaEtajj": ["HiggsLeading", "dEta"],
        "higgs2_DeltaEtajj": ["HiggsSubLeading", "dEta"],
        "minDeltaR_Higgjj": ["events", "dR_min"],
        "maxDeltaR_Higgjj": ["events", "dR_max"],
        "higgs1_helicityCosTheta": ["HiggsLeading", "helicityCosTheta"],
        "higgs2_helicityCosTheta": ["HiggsSubLeading", "helicityCosTheta"],
        "higgs1_reco_jet1_pt": ["JetGoodFromHiggsOrdered:0", "pt"],
        "higgs1_reco_jet1_eta": ["JetGoodFromHiggsOrdered:0", "eta"],
        "higgs1_reco_jet1_phi": ["JetGoodFromHiggsOrdered:0", "phi"],
        "higgs1_reco_jet1_mass": ["JetGoodFromHiggsOrdered:0", "mass"],
        "higgs1_reco_jet2_pt": ["JetGoodFromHiggsOrdered:1", "pt"],
        "higgs1_reco_jet2_eta": ["JetGoodFromHiggsOrdered:1", "eta"],
        "higgs1_reco_jet2_phi": ["JetGoodFromHiggsOrdered:1", "phi"],
        "higgs1_reco_jet2_mass": ["JetGoodFromHiggsOrdered:1", "mass"],
        "higgs2_reco_jet1_pt": ["JetGoodFromHiggsOrdered:2", "pt"],
        "higgs2_reco_jet1_eta": ["JetGoodFromHiggsOrdered:2", "eta"],
        "higgs2_reco_jet1_phi": ["JetGoodFromHiggsOrdered:2", "phi"],
        "higgs2_reco_jet1_mass": ["JetGoodFromHiggsOrdered:2", "mass"],
        "higgs2_reco_jet2_pt": ["JetGoodFromHiggsOrdered:3", "pt"],
        "higgs2_reco_jet2_eta": ["JetGoodFromHiggsOrdered:3", "eta"],
        "higgs2_reco_jet2_phi": ["JetGoodFromHiggsOrdered:3", "phi"],
        "higgs2_reco_jet2_mass": ["JetGoodFromHiggsOrdered:3", "mass"],
        "add_jet1pt_pt": ["add_jet1pt", "pt"],
        "add_jet1pt_eta": ["add_jet1pt", "eta"],
        "add_jet1pt_phi": ["add_jet1pt", "phi"],
        "add_jet1pt_mass": ["add_jet1pt", "mass"],
        "add_jet1pt_Higgs1_deta": ["add_jet1pt", "LeadingHiggs_dEta"],
        "add_jet1pt_Higgs1_dphi": ["add_jet1pt", "LeadingHiggs_dPhi"],
        "add_jet1pt_Higgs1_m": ["add_jet1pt", "LeadingHiggs_mass"],
        "add_jet1pt_Higgs2_deta": ["add_jet1pt", "SubLeadingHiggs_dEta"],
        "add_jet1pt_Higgs2_dphi": ["add_jet1pt", "SubLeadingHiggs_dPhi"],
        "add_jet1pt_Higgs2_m": ["add_jet1pt", "SubLeadingHiggs_mass"],
        "sigma_over_higgs1_reco_mass": ["events", "sigma_over_higgs1_reco_mass"],
        "sigma_over_higgs2_reco_mass": ["events", "sigma_over_higgs2_reco_mass"],
    }
)

bkg_morphing_boosted_dnn_input_variables_other_group = OrderedDict(
    {
        "vbf_cand_jets_pt_jet0": ["JetGoodVBFEnergyOrdered:0", "pt"],
        "vbf_cand_jets_eta_jet0": ["JetGoodVBFEnergyOrdered:0", "eta"],
        "vbf_cand_jets_phi_jet0": ["JetGoodVBFEnergyOrdered:0", "phi"],
        "vbf_cand_jets_mass_jet0": ["JetGoodVBFEnergyOrdered:0", "mass"],
        "vbf_cand_jets_pt_jet1": ["JetGoodVBFEnergyOrdered:1", "pt"],
        "vbf_cand_jets_eta_jet1": ["JetGoodVBFEnergyOrdered:1", "eta"],
        "vbf_cand_jets_phi_jet1": ["JetGoodVBFEnergyOrdered:1", "phi"],
        "vbf_cand_jets_mass_jet1": ["JetGoodVBFEnergyOrdered:1", "mass"],
        "HT": ["events", "HT"],
        "hh_vec_pt": ["HH", "pt"],
        "hh_vec_eta": ["HH", "eta"],
        "hh_vec_mass": ["HH", "mass"],
        "hh_vec_phi": ["HH", "phi"],
        "hh_vec_DeltaR": ["HH", "dR"],
        "hh_vec_DeltaPhi": ["HH", "dPhi"],
        "hh_vec_DeltaEta": ["HH", "dEta"],
        "hh_CosThetaStar_CS": ["HH", "Costhetastar_CS"],
        "higgs1_tau2overtau3": ["HiggsLeading", "Tau3OverTau2"],
        "higgs2_tau2overtau3": ["HiggsSubLeading", "Tau3OverTau2"],
        "higgs1_reco_pt": ["HiggsLeading", "pt"],
        "higgs1_reco_eta": ["HiggsLeading", "eta"],
        "higgs1_reco_phi": ["HiggsLeading", "phi"],
        "higgs1_reco_mass": ["HiggsLeading", "mass"],
        "higgs1_btag_dig": ["HiggsLeading", "btagBBTXbb_dig"],
        "higgs1_centrality": ["HiggsLeading", "centrality"],
        "higgs2_reco_pt": ["HiggsSubLeading", "pt"],
        "higgs2_reco_eta": ["HiggsSubLeading", "eta"],
        "higgs2_reco_phi": ["HiggsSubLeading", "phi"],
        # "higgs2_reco_mass": ["HiggsSubLeading", "mass"],
        # "higgs2_btag_dig": ["HiggsSubLeading", "btagBBTXbb"],
        "higgs2_centrality": ["HiggsSubLeading", "centrality"],
        "higgs1_divHHmass": ["HiggsLeading", "divHHmass"],
        "higgs1byhiggs2pt": ["events", "HiggsLeadingByHiggsSubLeadingPt"],
        "mjj": ["events", "mjjJetGoodVBFEnergyOrdered"],
        "deta": ["events", "detaJetGoodVBFEnergyOrdered"],
        "higgs1_dRclosestVBF": ["HiggsLeading", "dRclosestVBF"],
        "higgs2_dRclosestVBF": ["HiggsSubLeading", "dRclosestVBF"],
        "higgs1_massclosestVBF": ["HiggsLeading", "massclosestVBF"],
        "higgs2_massclosestVBF": ["HiggsSubLeading", "massclosestVBF"],
        "puppimet_pt": ["PuppiMET", "pt"],
        "met_et": ["PuppiMET", "sumEt"],
    }
)

bkg_morphing_boosted_dnn_input_variables = OrderedDict(
    {
        # "vbf_cand_jets_pt": ["JetGoodVBFCandidates", "pt"],
        # "vbf_cand_jets_eta": ["JetGoodVBFCandidates", "eta"],
        # "vbf_cand_jets_phi": ["JetGoodVBFCandidates", "phi"],
        # "vbf_cand_jets_mass": ["JetGoodVBFCandidates", "mass"],
        "vbf_cand_jets_pt_jet0": ["JetGoodVBF:0", "pt"],
        "vbf_cand_jets_eta_jet0": ["JetGoodVBF:0", "eta"],
        "vbf_cand_jets_phi_jet0": ["JetGoodVBF:0", "phi"],
        "vbf_cand_jets_mass_jet0": ["JetGoodVBF:0", "mass"],
        "vbf_cand_jets_pt_jet1": ["JetGoodVBF:1", "pt"],
        "vbf_cand_jets_eta_jet1": ["JetGoodVBF:1", "eta"],
        "vbf_cand_jets_phi_jet1": ["JetGoodVBF:1", "phi"],
        "vbf_cand_jets_mass_jet1": ["JetGoodVBF:1", "mass"],
        "vbf_cand_jets_pt_jet2": ["JetGoodVBF:2", "pt"],
        "vbf_cand_jets_eta_jet2": ["JetGoodVBF:2", "eta"],
        "vbf_cand_jets_phi_jet2": ["JetGoodVBF:2", "phi"],
        "vbf_cand_jets_mass_jet2": ["JetGoodVBF:2", "mass"],
        "vbf_cand_jets_pt_jet3": ["JetGoodVBF:3", "pt"],
        "vbf_cand_jets_eta_jet3": ["JetGoodVBF:3", "eta"],
        "vbf_cand_jets_phi_jet3": ["JetGoodVBF:3", "phi"],
        "vbf_cand_jets_mass_jet3": ["JetGoodVBF:3", "mass"],
        # "era": ["events", "era"],
        "HT": ["events", "HT"],
        "dijet_dEta": ["events", "dEta"],
        "higgs1_reco_pt": ["HiggsLeading", "pt"],
        "higgs1_reco_eta": ["HiggsLeading", "eta"],
        "higgs1_reco_phi": ["HiggsLeading", "phi"],
        # "higgs1_reco_mass": ["HiggsLeading", "mass"],
        "higgs1_centrality": ["HiggsLeading", "centrality"],
        "higgs1_btagBB_wp": ["HiggsLeading", "btagBB_3wp"],
        "higgs1_btagBB": ["HiggsLeading", "btagBB"],
        "higgs2_reco_pt": ["HiggsSubLeading", "pt"],
        "higgs2_reco_eta": ["HiggsSubLeading", "eta"],
        "higgs2_reco_phi": ["HiggsSubLeading", "phi"],
        "higgs2_reco_mass": ["HiggsSubLeading", "mass"],
        "higgs2_centrality": ["HiggsSubLeading", "centrality"],
        # "higgs2_btagBB_wp": ["HiggsSubLeading", "btagBB_3wp"],
        # "higgs2_btagBB": ["HiggsSubLeading", "btagBB"],
        "higgs1_DeltaR_Hj": ["HiggsLeading", "dR_Hjet_min"],
        "higgs1_mass_Hj": ["HiggsLeading", "m_Hjet_min_dR"],
        "higgs2_DeltaR_Hj": ["HiggsSubLeading", "dR_Hjet_min"],
        "higgs2_mass_Hj": ["HiggsSubLeading", "m_Hjet_min_dR"],
        "hh_CosThetaStar_CS": ["HH", "Costhetastar_CS"],
        "hh_vec_mass": ["HH", "mass"],
        "hh_vec_pt": ["HH", "pt"],
        "hh_vec_eta": ["HH", "eta"],
        "hh_vec_phi": ["HH", "phi"],
        "hh_vec_DeltaR": ["HH", "dR"],
        "hh_vec_DeltaPhi": ["HH", "dPhi"],
        "hh_vec_DeltaEta": ["HH", "dEta"],
        "dijet_LeadingJet_pt": ["LeadingVBFJet", "pt"],
        "dijet_LeadingJet_eta": ["LeadingVBFJet", "eta"],
        "dijet_LeadingJet_phi": ["LeadingVBFJet", "phi"],
        "dijet_LeadingJet_mass": ["LeadingVBFJet", "mass"],
        "dijet_SubLeadingJet_pt": ["SubLeadingVBFJet", "pt"],
        "dijet_SubLeadingJet_eta": ["SubLeadingVBFJet", "eta"],
        "dijet_SubLeadingJet_phi": ["SubLeadingVBFJet", "phi"],
        "dijet_SubLeadingJet_mass": ["SubLeadingVBFJet", "mass"],
        "met_et": ["PuppiMET", "sumEt"],
    }
)



#### Signal VS Background Variables ####

sig_bkg_dnn_input_variables = OrderedDict(
    {
        # "year": ["events", "year"],
        "HT": ["events", "HT"],
        "hh_vec_mass": ["HH", "mass"],
        "hh_vec_pt": ["HH", "pt"],
        "hh_vec_eta": ["HH", "eta"],
        "hh_vec_phi": ["HH", "phi"],
        "hh_vec_DeltaPhi": ["HH", "dPhi"],
        "hh_vec_DeltaEta": ["HH", "dEta"],
        "hh_vec_DeltaR": ["HH", "dR"],
        "hh_CosThetaStar_CS": ["HH", "Costhetastar_CS"],
        "higgs1_reco_pt": ["HiggsLeading", "pt"],
        "higgs1_reco_eta": ["HiggsLeading", "eta"],
        "higgs1_reco_phi": ["HiggsLeading", "phi"],
        "higgs1_reco_mass": ["HiggsLeading", "mass"],
        "higgs2_reco_pt": ["HiggsSubLeading", "pt"],
        "higgs2_reco_eta": ["HiggsSubLeading", "eta"],
        "higgs2_reco_phi": ["HiggsSubLeading", "phi"],
        "higgs2_reco_mass": ["HiggsSubLeading", "mass"],
        "higgs1_DeltaPhijj": ["HiggsLeading", "dPhi"],
        "higgs2_DeltaPhijj": ["HiggsSubLeading", "dPhi"],
        "higgs1_DeltaEtajj": ["HiggsLeading", "dEta"],
        "higgs2_DeltaEtajj": ["HiggsSubLeading", "dEta"],
        "minDeltaR_Higgjj": ["events", "dR_min"],
        "maxDeltaR_Higgjj": ["events", "dR_max"],
        "higgs1_helicityCosTheta": ["HiggsLeading", "helicityCosTheta"],
        "higgs2_helicityCosTheta": ["HiggsSubLeading", "helicityCosTheta"],
        "higgs1_reco_jet1_pt": ["JetGoodFromHiggsOrdered:0", "pt"],
        "higgs1_reco_jet1_eta": ["JetGoodFromHiggsOrdered:0", "eta"],
        "higgs1_reco_jet1_phi": ["JetGoodFromHiggsOrdered:0", "phi"],
        "higgs1_reco_jet1_mass": ["JetGoodFromHiggsOrdered:0", "mass"],
        "higgs1_reco_jet2_pt": ["JetGoodFromHiggsOrdered:1", "pt"],
        "higgs1_reco_jet2_eta": ["JetGoodFromHiggsOrdered:1", "eta"],
        "higgs1_reco_jet2_phi": ["JetGoodFromHiggsOrdered:1", "phi"],
        "higgs1_reco_jet2_mass": ["JetGoodFromHiggsOrdered:1", "mass"],
        "higgs2_reco_jet1_pt": ["JetGoodFromHiggsOrdered:2", "pt"],
        "higgs2_reco_jet1_eta": ["JetGoodFromHiggsOrdered:2", "eta"],
        "higgs2_reco_jet1_phi": ["JetGoodFromHiggsOrdered:2", "phi"],
        "higgs2_reco_jet1_mass": ["JetGoodFromHiggsOrdered:2", "mass"],
        "higgs2_reco_jet2_pt": ["JetGoodFromHiggsOrdered:3", "pt"],
        "higgs2_reco_jet2_eta": ["JetGoodFromHiggsOrdered:3", "eta"],
        "higgs2_reco_jet2_phi": ["JetGoodFromHiggsOrdered:3", "phi"],
        "higgs2_reco_jet2_mass": ["JetGoodFromHiggsOrdered:3", "mass"],
        "add_jet1pt_pt": ["add_jet1pt", "pt"],
        "add_jet1pt_eta": ["add_jet1pt", "eta"],
        "add_jet1pt_phi": ["add_jet1pt", "phi"],
        "add_jet1pt_mass": ["add_jet1pt", "mass"],
        "add_jet1pt_Higgs1_deta": ["add_jet1pt", "LeadingHiggs_dEta"],
        "add_jet1pt_Higgs1_dphi": ["add_jet1pt", "LeadingHiggs_dPhi"],
        "add_jet1pt_Higgs1_m": ["add_jet1pt", "LeadingHiggs_mass"],
        "add_jet1pt_Higgs2_deta": ["add_jet1pt", "SubLeadingHiggs_dEta"],
        "add_jet1pt_Higgs2_dphi": ["add_jet1pt", "SubLeadingHiggs_dPhi"],
        "add_jet1pt_Higgs2_m": ["add_jet1pt", "SubLeadingHiggs_mass"],
        "sigma_over_higgs1_reco_mass": ["events", "sigma_over_higgs1_reco_mass"],
        "sigma_over_higgs2_reco_mass": ["events", "sigma_over_higgs2_reco_mass"],
    }
)
pairing_spanet_nobtag = OrderedDict(
    {
        "sequential": {
            "jet_log_pt": ["JetGood", "pt", "log_norm"],
            "jet_eta": ["JetGood", "eta", "norm"],
            "jet_phi": ["JetGood", "phi", "norm"],
            },
        "global": {
            }
    }
)
pairing_spanet_btagWP = OrderedDict(
    {
        "sequential": {
            "jet_log_pt": ["JetGood", "pt", "log_norm"],
            "jet_eta": ["JetGood", "eta", "norm"],
            "jet_phi": ["JetGood", "phi", "norm"],
            "jet_btag_wp": ["JetGood", "btagPNetB_wp"],
            },
        "global": {
            }
    }
)
pairing_spanet_btagWP5 = OrderedDict(
    {
        "sequential": {
            "jet_log_pt": ["JetGood", "pt", "log_norm"],
            "jet_eta": ["JetGood", "eta", "norm"],
            "jet_phi": ["JetGood", "phi", "norm"],
            "jet_btag_5wp": ["JetGood", "btagPNetB_5wp"],
            },
        "global": {
            }
    }
)
pairing_spanet_btagWP3 = OrderedDict(
    {
        "sequential": {
            "jet_log_pt": ["JetGood", "pt", "log_norm"],
            "jet_eta": ["JetGood", "eta", "norm"],
            "jet_phi": ["JetGood", "phi", "norm"],
            "jet_btag_3wp": ["JetGood", "btagPNetB_3wp"],
            },
        "global": {
            }
    }
)

pairing_spanet_btagDeltaWP5 = OrderedDict(
    {
        "sequential": {
            "jet_log_pt": ["JetGood", "pt", "log_norm"],
            "jet_eta": ["JetGood", "eta", "norm"],
            "jet_phi": ["JetGood", "phi", "norm"],
            "jet_btag_delta5wp": ["JetGood", "btagPNetB_delta5wp"],
            },
        "global": {
            }
    }
)

pairing_spanet_btag12_ratioSubLead = OrderedDict(
    {
        "sequential": {
            "jet_log_pt": ["JetGood", "pt", "log_norm"],
            "jet_eta": ["JetGood", "eta", "norm"],
            "jet_phi": ["JetGood", "phi", "norm"],
            "jet_btag12_ratioSubLead": ["JetGood", "btag12_ratioSubLead"],
            },
        "global": {
            }
    }
)

pairing_spanet_btag = OrderedDict(
    {
        "sequential": {
            "jet_log_pt": ["JetGood", "pt", "log_norm"],
            "jet_eta": ["JetGood", "eta", "norm"],
            "jet_phi": ["JetGood", "phi", "norm"],
            "jet_btag": ["JetGood", "btagPNetB"],
            },
        "global": {
            }
    }
)

pairing_spanet_btag_ratioAll = OrderedDict(
    {
        "sequential": {
            "jet_log_pt": ["JetGood", "pt", "log_norm"],
            "jet_eta": ["JetGood", "eta", "norm"],
            "jet_phi": ["JetGood", "phi", "norm"],
            "jet_btag_ratioAll": ["JetGood", "btag_ratioAll"],
            },
        "global": {
            }
    }
)

pairing_spanet_vbf_ggf_btagWP5 = OrderedDict(
    {
        "sequential": {
            "jet_log_pt": ["JetTotalSPANetPadded", "pt", "log_norm"],
            "jet_eta": ["JetTotalSPANetPadded", "eta", "norm"],
            "jet_phi": ["JetTotalSPANetPadded", "phi", "norm"],
            "jet_btag_5wp": ["JetTotalSPANetPadded", "btagPNetB_5wp"],
            },
        "global": {
            }
    }
)

sig_bkg_dnn_input_variables_spanet = OrderedDict(
    {
        "sequential": {
            "jet_log_pt": ["JetGoodFromHiggsOrdered5Jets", "pt", "log_norm"],
            "jet_eta": ["JetGoodFromHiggsOrdered5Jets", "eta", "norm"],
            "jet_phi": ["JetGoodFromHiggsOrdered5Jets", "phi", "norm"],
            "jet_log_mass": ["JetGoodFromHiggsOrdered5Jets", "mass", "log_norm"],
            },
        "global": {
            # "Arctanh_Delta_pairing_probabilities": ["events", "Arctanh_Delta_pairing_probabilities"],
            "maxDeltaR_Higgjj": ["events", "dR_max"],
            "minDeltaR_Higgjj": ["events", "dR_min"],
            "HT": ["events", "HT", "log_norm"],
            "higgs1_reco_pt": ["HiggsLeading", "pt", "log_norm"],
            "higgs1_reco_eta": ["HiggsLeading", "eta"],
            "higgs1_reco_phi": ["HiggsLeading", "phi"],
            "higgs1_reco_mass": ["HiggsLeading", "mass", "log_norm"],
            "higgs1_reco_dR": ["HiggsLeading", "dR"],
            "higgs1_helicityCosTheta": ["HiggsLeading", "helicityCosTheta"],
            "higgs2_reco_pt": ["HiggsSubLeading", "pt", "log_norm"],
            "higgs2_reco_eta": ["HiggsSubLeading", "eta"],
            "higgs2_reco_phi": ["HiggsSubLeading", "phi"],
            "higgs2_reco_mass": ["HiggsSubLeading", "mass", "log_norm"],
            "higgs2_reco_dR": ["HiggsSubLeading", "dR"],
            "higgs2_helicityCosTheta": ["HiggsSubLeading", "helicityCosTheta"],
            "hh_vec_pt": ["HH", "pt", "log_norm"],
            "hh_vec_eta": ["HH", "eta", "norm"],
            "hh_vec_phi": ["HH", "phi"],
            "hh_vec_mass": ["HH", "mass", "log_norm"],
            "hh_vec_DeltaR": ["HH", "dR"],
            "hh_vec_DeltaEta": ["HH", "dEta"],
            "hh_vec_DeltaPhi": ["HH", "dPhi"],
            }
    }
)


sig_bkg_dnn_input_variables_spanet_AN23_184_vars = OrderedDict(
    {
        "sequential": {
            "jet_eta": ["JetGoodFromHiggsOrdered5Jets", "eta", "norm"],
            "jet_log_mass": ["JetGoodFromHiggsOrdered5Jets", "mass", "log_norm"],
            "jet_phi": ["JetGoodFromHiggsOrdered5Jets", "phi", "norm"],
            "jet_log_pt": ["JetGoodFromHiggsOrdered5Jets", "pt", "log_norm"],
            },
        "global": {
            "HT": ["events", "HT", "log_norm"],
            "maxDeltaR_Higgjj": ["events", "dR_max", "norm"],
            "minDeltaR_Higgjj": ["events", "dR_min", "norm"],
            "sigma_over_higgs1_reco_mass": ["events", "sigma_over_higgs1_reco_mass", "norm"],
            "sigma_over_higgs2_reco_mass": ["events", "sigma_over_higgs2_reco_mass", "norm"],
            "higgs1_DeltaEtajj": ["HiggsLeading", "dEta", "norm"],
            "higgs1_DeltaPhijj": ["HiggsLeading", "dPhi", "norm"],
            # "higgs1_reco_dR": ["HiggsLeading", "dR", "norm"],
            "higgs1_reco_eta": ["HiggsLeading", "eta", "norm"],
            "higgs1_helicityCosTheta": ["HiggsLeading", "helicityCosTheta", "norm"],
            "higgs1_reco_phi": ["HiggsLeading", "phi", "norm"],
            "higgs1_reco_mass": ["HiggsLeading", "mass", "log_norm"],
            "higgs1_reco_pt": ["HiggsLeading", "pt", "log_norm"],
            "higgs2_DeltaEtajj": ["HiggsSubLeading", "dEta", "norm"],
            "higgs2_DeltaPhijj": ["HiggsSubLeading", "dPhi", "norm"],
            # "higgs2_reco_dR": ["HiggsSubLeading", "dR", "norm"],
            "higgs2_reco_eta": ["HiggsSubLeading", "eta", "norm"],
            "higgs2_helicityCosTheta": ["HiggsSubLeading", "helicityCosTheta", "norm"],
            "higgs2_reco_phi": ["HiggsSubLeading", "phi", "norm"],
            "higgs2_reco_mass": ["HiggsSubLeading", "mass", "log_norm"],
            "higgs2_reco_pt": ["HiggsSubLeading", "pt", "log_norm"],
            "hh_CosThetaStar_CS": ["HH", "Costhetastar_CS", "norm"],
            "hh_vec_DeltaEta": ["HH", "dEta", "norm"],
            "hh_vec_DeltaPhi": ["HH", "dPhi", "norm"],
            "hh_vec_DeltaR": ["HH", "dR", "norm"],
            "hh_vec_eta": ["HH", "eta", "norm"],
            "hh_vec_mass": ["HH", "mass", "log_norm"],
            "hh_vec_phi": ["HH", "phi", "norm"],
            "hh_vec_pt": ["HH", "pt", "log_norm"],
            "add_jet1pt_Higgs1_deta": ["add_jet1pt", "LeadingHiggs_dEta", "norm"],
            "add_jet1pt_Higgs1_dphi": ["add_jet1pt", "LeadingHiggs_dPhi", "norm"],
            "add_jet1pt_Higgs1_m": ["add_jet1pt", "LeadingHiggs_mass", "norm"],
            "add_jet1pt_Higgs2_deta": ["add_jet1pt", "SubLeadingHiggs_dEta", "norm"],
            "add_jet1pt_Higgs2_dphi": ["add_jet1pt", "SubLeadingHiggs_dPhi", "norm"],
            "add_jet1pt_Higgs2_m": ["add_jet1pt", "SubLeadingHiggs_mass", "norm"],
            "add_jet1pt_eta": ["add_jet1pt", "eta", "norm"],
            "add_jet1pt_mass": ["add_jet1pt", "mass", "norm"],
            "add_jet1pt_phi": ["add_jet1pt", "phi", "norm"],
            "add_jet1pt_pt": ["add_jet1pt", "pt", "norm"],
            }
    }
)


sig_bkg_dnn_DeltaProb_input_variables = OrderedDict(
    {
        # "year": ["events", "year"],
        "Delta_pairing_probabilities": ["events", "Delta_pairing_probabilities"],
        "HT": ["events", "HT"],
        "hh_vec_mass": ["HH", "mass"],
        "hh_vec_pt": ["HH", "pt"],
        "hh_vec_eta": ["HH", "eta"],
        "hh_vec_phi": ["HH", "phi"],
        "hh_vec_DeltaPhi": ["HH", "dPhi"],
        "hh_vec_DeltaEta": ["HH", "dEta"],
        "hh_vec_DeltaR": ["HH", "dR"],
        "hh_CosThetaStar_CS": ["HH", "Costhetastar_CS"],
        "higgs1_reco_pt": ["HiggsLeading", "pt"],
        "higgs1_reco_eta": ["HiggsLeading", "eta"],
        "higgs1_reco_phi": ["HiggsLeading", "phi"],
        "higgs1_reco_mass": ["HiggsLeading", "mass"],
        "higgs2_reco_pt": ["HiggsSubLeading", "pt"],
        "higgs2_reco_eta": ["HiggsSubLeading", "eta"],
        "higgs2_reco_phi": ["HiggsSubLeading", "phi"],
        "higgs2_reco_mass": ["HiggsSubLeading", "mass"],
        "higgs1_DeltaPhijj": ["HiggsLeading", "dPhi"],
        "higgs2_DeltaPhijj": ["HiggsSubLeading", "dPhi"],
        "higgs1_DeltaEtajj": ["HiggsLeading", "dEta"],
        "higgs2_DeltaEtajj": ["HiggsSubLeading", "dEta"],
        "minDeltaR_Higgjj": ["events", "dR_min"],
        "maxDeltaR_Higgjj": ["events", "dR_max"],
        "higgs1_helicityCosTheta": ["HiggsLeading", "helicityCosTheta"],
        "higgs2_helicityCosTheta": ["HiggsSubLeading", "helicityCosTheta"],
        "higgs1_reco_jet1_pt": ["JetGoodFromHiggsOrdered:0", "pt"],
        "higgs1_reco_jet1_eta": ["JetGoodFromHiggsOrdered:0", "eta"],
        "higgs1_reco_jet1_phi": ["JetGoodFromHiggsOrdered:0", "phi"],
        "higgs1_reco_jet1_mass": ["JetGoodFromHiggsOrdered:0", "mass"],
        "higgs1_reco_jet2_pt": ["JetGoodFromHiggsOrdered:1", "pt"],
        "higgs1_reco_jet2_eta": ["JetGoodFromHiggsOrdered:1", "eta"],
        "higgs1_reco_jet2_phi": ["JetGoodFromHiggsOrdered:1", "phi"],
        "higgs1_reco_jet2_mass": ["JetGoodFromHiggsOrdered:1", "mass"],
        "higgs2_reco_jet1_pt": ["JetGoodFromHiggsOrdered:2", "pt"],
        "higgs2_reco_jet1_eta": ["JetGoodFromHiggsOrdered:2", "eta"],
        "higgs2_reco_jet1_phi": ["JetGoodFromHiggsOrdered:2", "phi"],
        "higgs2_reco_jet1_mass": ["JetGoodFromHiggsOrdered:2", "mass"],
        "higgs2_reco_jet2_pt": ["JetGoodFromHiggsOrdered:3", "pt"],
        "higgs2_reco_jet2_eta": ["JetGoodFromHiggsOrdered:3", "eta"],
        "higgs2_reco_jet2_phi": ["JetGoodFromHiggsOrdered:3", "phi"],
        "higgs2_reco_jet2_mass": ["JetGoodFromHiggsOrdered:3", "mass"],
        "add_jet1pt_pt": ["add_jet1pt", "pt"],
        "add_jet1pt_eta": ["add_jet1pt", "eta"],
        "add_jet1pt_phi": ["add_jet1pt", "phi"],
        "add_jet1pt_mass": ["add_jet1pt", "mass"],
        "add_jet1pt_Higgs1_deta": ["add_jet1pt", "LeadingHiggs_dEta"],
        "add_jet1pt_Higgs1_dphi": ["add_jet1pt", "LeadingHiggs_dPhi"],
        "add_jet1pt_Higgs1_m": ["add_jet1pt", "LeadingHiggs_mass"],
        "add_jet1pt_Higgs2_deta": ["add_jet1pt", "SubLeadingHiggs_dEta"],
        "add_jet1pt_Higgs2_dphi": ["add_jet1pt", "SubLeadingHiggs_dPhi"],
        "add_jet1pt_Higgs2_m": ["add_jet1pt", "SubLeadingHiggs_mass"],
        "sigma_over_higgs1_reco_mass": ["events", "sigma_over_higgs1_reco_mass"],
        "sigma_over_higgs2_reco_mass": ["events", "sigma_over_higgs2_reco_mass"],
    }
)

sig_bkg_dnn_DeltaProb_input_variables_less_add_jet1pt_vars = OrderedDict(
    {
        # "year": ["events", "year"],
        "Delta_pairing_probabilities": ["events", "Delta_pairing_probabilities"],
        "HT": ["events", "HT"],
        "hh_vec_mass": ["HH", "mass"],
        "hh_vec_pt": ["HH", "pt"],
        "hh_vec_eta": ["HH", "eta"],
        "hh_vec_phi": ["HH", "phi"],
        "hh_vec_DeltaPhi": ["HH", "dPhi"],
        "hh_vec_DeltaEta": ["HH", "dEta"],
        "hh_vec_DeltaR": ["HH", "dR"],
        "hh_CosThetaStar_CS": ["HH", "Costhetastar_CS"],
        "higgs1_reco_pt": ["HiggsLeading", "pt"],
        "higgs1_reco_eta": ["HiggsLeading", "eta"],
        "higgs1_reco_phi": ["HiggsLeading", "phi"],
        "higgs1_reco_mass": ["HiggsLeading", "mass"],
        "higgs2_reco_pt": ["HiggsSubLeading", "pt"],
        "higgs2_reco_eta": ["HiggsSubLeading", "eta"],
        "higgs2_reco_phi": ["HiggsSubLeading", "phi"],
        "higgs2_reco_mass": ["HiggsSubLeading", "mass"],
        "higgs1_DeltaPhijj": ["HiggsLeading", "dPhi"],
        "higgs2_DeltaPhijj": ["HiggsSubLeading", "dPhi"],
        "higgs1_DeltaEtajj": ["HiggsLeading", "dEta"],
        "higgs2_DeltaEtajj": ["HiggsSubLeading", "dEta"],
        "minDeltaR_Higgjj": ["events", "dR_min"],
        "maxDeltaR_Higgjj": ["events", "dR_max"],
        "higgs1_helicityCosTheta": ["HiggsLeading", "helicityCosTheta"],
        "higgs2_helicityCosTheta": ["HiggsSubLeading", "helicityCosTheta"],
        "higgs1_reco_jet1_pt": ["JetGoodFromHiggsOrdered:0", "pt"],
        "higgs1_reco_jet1_eta": ["JetGoodFromHiggsOrdered:0", "eta"],
        "higgs1_reco_jet1_phi": ["JetGoodFromHiggsOrdered:0", "phi"],
        "higgs1_reco_jet1_mass": ["JetGoodFromHiggsOrdered:0", "mass"],
        "higgs1_reco_jet2_pt": ["JetGoodFromHiggsOrdered:1", "pt"],
        "higgs1_reco_jet2_eta": ["JetGoodFromHiggsOrdered:1", "eta"],
        "higgs1_reco_jet2_phi": ["JetGoodFromHiggsOrdered:1", "phi"],
        "higgs1_reco_jet2_mass": ["JetGoodFromHiggsOrdered:1", "mass"],
        "higgs2_reco_jet1_pt": ["JetGoodFromHiggsOrdered:2", "pt"],
        "higgs2_reco_jet1_eta": ["JetGoodFromHiggsOrdered:2", "eta"],
        "higgs2_reco_jet1_phi": ["JetGoodFromHiggsOrdered:2", "phi"],
        "higgs2_reco_jet1_mass": ["JetGoodFromHiggsOrdered:2", "mass"],
        "higgs2_reco_jet2_pt": ["JetGoodFromHiggsOrdered:3", "pt"],
        "higgs2_reco_jet2_eta": ["JetGoodFromHiggsOrdered:3", "eta"],
        "higgs2_reco_jet2_phi": ["JetGoodFromHiggsOrdered:3", "phi"],
        "higgs2_reco_jet2_mass": ["JetGoodFromHiggsOrdered:3", "mass"],
        "add_jet1pt_pt": ["add_jet1pt", "pt"],
        "add_jet1pt_eta": ["add_jet1pt", "eta"],
        "add_jet1pt_phi": ["add_jet1pt", "phi"],
        "add_jet1pt_mass": ["add_jet1pt", "mass"],
        #        "add_jet1pt_Higgs1_deta": ["add_jet1pt", "LeadingHiggs_dEta"],
        #        "add_jet1pt_Higgs1_dphi": ["add_jet1pt", "LeadingHiggs_dPhi"],
        #        "add_jet1pt_Higgs1_m": ["add_jet1pt", "LeadingHiggs_mass"],
        #        "add_jet1pt_Higgs2_deta": ["add_jet1pt", "SubLeadingHiggs_dEta"],
        #        "add_jet1pt_Higgs2_dphi": ["add_jet1pt", "SubLeadingHiggs_dPhi"],
        #        "add_jet1pt_Higgs2_m": ["add_jet1pt", "SubLeadingHiggs_mass"],
        "sigma_over_higgs1_reco_mass": ["events", "sigma_over_higgs1_reco_mass"],
        "sigma_over_higgs2_reco_mass": ["events", "sigma_over_higgs2_reco_mass"],
    }
)

sig_bkg_dnn_ArctanhDeltaProb_input_variables = OrderedDict(
    {
        # "year": ["events", "year"],
        "Arctanh_Delta_pairing_probabilities": [
            "events",
            "Arctanh_Delta_pairing_probabilities",
        ],
        "HT": ["events", "HT"],
        "hh_vec_mass": ["HH", "mass"],
        "hh_vec_pt": ["HH", "pt"],
        "hh_vec_eta": ["HH", "eta"],
        "hh_vec_phi": ["HH", "phi"],
        "hh_vec_DeltaPhi": ["HH", "dPhi"],
        "hh_vec_DeltaEta": ["HH", "dEta"],
        "hh_vec_DeltaR": ["HH", "dR"],
        "hh_CosThetaStar_CS": ["HH", "Costhetastar_CS"],
        "higgs1_reco_pt": ["HiggsLeading", "pt"],
        "higgs1_reco_eta": ["HiggsLeading", "eta"],
        "higgs1_reco_phi": ["HiggsLeading", "phi"],
        "higgs1_reco_mass": ["HiggsLeading", "mass"],
        "higgs2_reco_pt": ["HiggsSubLeading", "pt"],
        "higgs2_reco_eta": ["HiggsSubLeading", "eta"],
        "higgs2_reco_phi": ["HiggsSubLeading", "phi"],
        "higgs2_reco_mass": ["HiggsSubLeading", "mass"],
        "higgs1_DeltaPhijj": ["HiggsLeading", "dPhi"],
        "higgs2_DeltaPhijj": ["HiggsSubLeading", "dPhi"],
        "higgs1_DeltaEtajj": ["HiggsLeading", "dEta"],
        "higgs2_DeltaEtajj": ["HiggsSubLeading", "dEta"],
        "minDeltaR_Higgjj": ["events", "dR_min"],
        "maxDeltaR_Higgjj": ["events", "dR_max"],
        "higgs1_helicityCosTheta": ["HiggsLeading", "helicityCosTheta"],
        "higgs2_helicityCosTheta": ["HiggsSubLeading", "helicityCosTheta"],
        "higgs1_reco_jet1_pt": ["JetGoodFromHiggsOrdered:0", "pt"],
        "higgs1_reco_jet1_eta": ["JetGoodFromHiggsOrdered:0", "eta"],
        "higgs1_reco_jet1_phi": ["JetGoodFromHiggsOrdered:0", "phi"],
        "higgs1_reco_jet1_mass": ["JetGoodFromHiggsOrdered:0", "mass"],
        "higgs1_reco_jet2_pt": ["JetGoodFromHiggsOrdered:1", "pt"],
        "higgs1_reco_jet2_eta": ["JetGoodFromHiggsOrdered:1", "eta"],
        "higgs1_reco_jet2_phi": ["JetGoodFromHiggsOrdered:1", "phi"],
        "higgs1_reco_jet2_mass": ["JetGoodFromHiggsOrdered:1", "mass"],
        "higgs2_reco_jet1_pt": ["JetGoodFromHiggsOrdered:2", "pt"],
        "higgs2_reco_jet1_eta": ["JetGoodFromHiggsOrdered:2", "eta"],
        "higgs2_reco_jet1_phi": ["JetGoodFromHiggsOrdered:2", "phi"],
        "higgs2_reco_jet1_mass": ["JetGoodFromHiggsOrdered:2", "mass"],
        "higgs2_reco_jet2_pt": ["JetGoodFromHiggsOrdered:3", "pt"],
        "higgs2_reco_jet2_eta": ["JetGoodFromHiggsOrdered:3", "eta"],
        "higgs2_reco_jet2_phi": ["JetGoodFromHiggsOrdered:3", "phi"],
        "higgs2_reco_jet2_mass": ["JetGoodFromHiggsOrdered:3", "mass"],
        "add_jet1pt_pt": ["add_jet1pt", "pt"],
        "add_jet1pt_eta": ["add_jet1pt", "eta"],
        "add_jet1pt_phi": ["add_jet1pt", "phi"],
        "add_jet1pt_mass": ["add_jet1pt", "mass"],
        "add_jet1pt_Higgs1_deta": ["add_jet1pt", "LeadingHiggs_dEta"],
        "add_jet1pt_Higgs1_dphi": ["add_jet1pt", "LeadingHiggs_dPhi"],
        "add_jet1pt_Higgs1_m": ["add_jet1pt", "LeadingHiggs_mass"],
        "add_jet1pt_Higgs2_deta": ["add_jet1pt", "SubLeadingHiggs_dEta"],
        "add_jet1pt_Higgs2_dphi": ["add_jet1pt", "SubLeadingHiggs_dPhi"],
        "add_jet1pt_Higgs2_m": ["add_jet1pt", "SubLeadingHiggs_mass"],
        "sigma_over_higgs1_reco_mass": ["events", "sigma_over_higgs1_reco_mass"],
        "sigma_over_higgs2_reco_mass": ["events", "sigma_over_higgs2_reco_mass"],
    }
)

sig_bkg_dnn_ArctanhDeltaProb_input_variables_less_add_jet1pt_vars = OrderedDict(
    {
        # "year": ["events", "year"],
        "Arctanh_Delta_pairing_probabilities": [
            "events",
            "Arctanh_Delta_pairing_probabilities",
        ],
        "HT": ["events", "HT"],
        "hh_vec_mass": ["HH", "mass"],
        "hh_vec_pt": ["HH", "pt"],
        "hh_vec_eta": ["HH", "eta"],
        "hh_vec_phi": ["HH", "phi"],
        "hh_vec_DeltaPhi": ["HH", "dPhi"],
        "hh_vec_DeltaEta": ["HH", "dEta"],
        "hh_vec_DeltaR": ["HH", "dR"],
        "hh_CosThetaStar_CS": ["HH", "Costhetastar_CS"],
        "higgs1_reco_pt": ["HiggsLeading", "pt"],
        "higgs1_reco_eta": ["HiggsLeading", "eta"],
        "higgs1_reco_phi": ["HiggsLeading", "phi"],
        "higgs1_reco_mass": ["HiggsLeading", "mass"],
        "higgs2_reco_pt": ["HiggsSubLeading", "pt"],
        "higgs2_reco_eta": ["HiggsSubLeading", "eta"],
        "higgs2_reco_phi": ["HiggsSubLeading", "phi"],
        "higgs2_reco_mass": ["HiggsSubLeading", "mass"],
        "higgs1_DeltaPhijj": ["HiggsLeading", "dPhi"],
        "higgs2_DeltaPhijj": ["HiggsSubLeading", "dPhi"],
        "higgs1_DeltaEtajj": ["HiggsLeading", "dEta"],
        "higgs2_DeltaEtajj": ["HiggsSubLeading", "dEta"],
        "minDeltaR_Higgjj": ["events", "dR_min"],
        "maxDeltaR_Higgjj": ["events", "dR_max"],
        "higgs1_helicityCosTheta": ["HiggsLeading", "helicityCosTheta"],
        "higgs2_helicityCosTheta": ["HiggsSubLeading", "helicityCosTheta"],
        "higgs1_reco_jet1_pt": ["JetGoodFromHiggsOrdered:0", "pt"],
        "higgs1_reco_jet1_eta": ["JetGoodFromHiggsOrdered:0", "eta"],
        "higgs1_reco_jet1_phi": ["JetGoodFromHiggsOrdered:0", "phi"],
        "higgs1_reco_jet1_mass": ["JetGoodFromHiggsOrdered:0", "mass"],
        "higgs1_reco_jet2_pt": ["JetGoodFromHiggsOrdered:1", "pt"],
        "higgs1_reco_jet2_eta": ["JetGoodFromHiggsOrdered:1", "eta"],
        "higgs1_reco_jet2_phi": ["JetGoodFromHiggsOrdered:1", "phi"],
        "higgs1_reco_jet2_mass": ["JetGoodFromHiggsOrdered:1", "mass"],
        "higgs2_reco_jet1_pt": ["JetGoodFromHiggsOrdered:2", "pt"],
        "higgs2_reco_jet1_eta": ["JetGoodFromHiggsOrdered:2", "eta"],
        "higgs2_reco_jet1_phi": ["JetGoodFromHiggsOrdered:2", "phi"],
        "higgs2_reco_jet1_mass": ["JetGoodFromHiggsOrdered:2", "mass"],
        "higgs2_reco_jet2_pt": ["JetGoodFromHiggsOrdered:3", "pt"],
        "higgs2_reco_jet2_eta": ["JetGoodFromHiggsOrdered:3", "eta"],
        "higgs2_reco_jet2_phi": ["JetGoodFromHiggsOrdered:3", "phi"],
        "higgs2_reco_jet2_mass": ["JetGoodFromHiggsOrdered:3", "mass"],
        "add_jet1pt_pt": ["add_jet1pt", "pt"],
        "add_jet1pt_eta": ["add_jet1pt", "eta"],
        "add_jet1pt_phi": ["add_jet1pt", "phi"],
        "add_jet1pt_mass": ["add_jet1pt", "mass"],
        #        "add_jet1pt_Higgs1_deta": ["add_jet1pt", "LeadingHiggs_dEta"],
        #        "add_jet1pt_Higgs1_dphi": ["add_jet1pt", "LeadingHiggs_dPhi"],
        #        "add_jet1pt_Higgs1_m": ["add_jet1pt", "LeadingHiggs_mass"],
        #        "add_jet1pt_Higgs2_deta": ["add_jet1pt", "SubLeadingHiggs_dEta"],
        #        "add_jet1pt_Higgs2_dphi": ["add_jet1pt", "SubLeadingHiggs_dPhi"],
        #        "add_jet1pt_Higgs2_m": ["add_jet1pt", "SubLeadingHiggs_mass"],
        "sigma_over_higgs1_reco_mass": ["events", "sigma_over_higgs1_reco_mass"],
        "sigma_over_higgs2_reco_mass": ["events", "sigma_over_higgs2_reco_mass"],
    }
)

sig_bkg_dnn_BinnedArctanhDeltaProb_input_variables = OrderedDict(
    {
        # "year": ["events", "year"],
        "Binned_Arctanh_Delta_pairing_probabilities": [
            "events",
            "Binned_Arctanh_Delta_pairing_probabilities",
        ],
        "HT": ["events", "HT"],
        "hh_vec_mass": ["HH", "mass"],
        "hh_vec_pt": ["HH", "pt"],
        "hh_vec_eta": ["HH", "eta"],
        "hh_vec_phi": ["HH", "phi"],
        "hh_vec_DeltaPhi": ["HH", "dPhi"],
        "hh_vec_DeltaEta": ["HH", "dEta"],
        "hh_vec_DeltaR": ["HH", "dR"],
        "hh_CosThetaStar_CS": ["HH", "Costhetastar_CS"],
        "higgs1_reco_pt": ["HiggsLeading", "pt"],
        "higgs1_reco_eta": ["HiggsLeading", "eta"],
        "higgs1_reco_phi": ["HiggsLeading", "phi"],
        "higgs1_reco_mass": ["HiggsLeading", "mass"],
        "higgs2_reco_pt": ["HiggsSubLeading", "pt"],
        "higgs2_reco_eta": ["HiggsSubLeading", "eta"],
        "higgs2_reco_phi": ["HiggsSubLeading", "phi"],
        "higgs2_reco_mass": ["HiggsSubLeading", "mass"],
        "higgs1_DeltaPhijj": ["HiggsLeading", "dPhi"],
        "higgs2_DeltaPhijj": ["HiggsSubLeading", "dPhi"],
        "higgs1_DeltaEtajj": ["HiggsLeading", "dEta"],
        "higgs2_DeltaEtajj": ["HiggsSubLeading", "dEta"],
        "minDeltaR_Higgjj": ["events", "dR_min"],
        "maxDeltaR_Higgjj": ["events", "dR_max"],
        "higgs1_helicityCosTheta": ["HiggsLeading", "helicityCosTheta"],
        "higgs2_helicityCosTheta": ["HiggsSubLeading", "helicityCosTheta"],
        "higgs1_reco_jet1_pt": ["JetGoodFromHiggsOrdered:0", "pt"],
        "higgs1_reco_jet1_eta": ["JetGoodFromHiggsOrdered:0", "eta"],
        "higgs1_reco_jet1_phi": ["JetGoodFromHiggsOrdered:0", "phi"],
        "higgs1_reco_jet1_mass": ["JetGoodFromHiggsOrdered:0", "mass"],
        "higgs1_reco_jet2_pt": ["JetGoodFromHiggsOrdered:1", "pt"],
        "higgs1_reco_jet2_eta": ["JetGoodFromHiggsOrdered:1", "eta"],
        "higgs1_reco_jet2_phi": ["JetGoodFromHiggsOrdered:1", "phi"],
        "higgs1_reco_jet2_mass": ["JetGoodFromHiggsOrdered:1", "mass"],
        "higgs2_reco_jet1_pt": ["JetGoodFromHiggsOrdered:2", "pt"],
        "higgs2_reco_jet1_eta": ["JetGoodFromHiggsOrdered:2", "eta"],
        "higgs2_reco_jet1_phi": ["JetGoodFromHiggsOrdered:2", "phi"],
        "higgs2_reco_jet1_mass": ["JetGoodFromHiggsOrdered:2", "mass"],
        "higgs2_reco_jet2_pt": ["JetGoodFromHiggsOrdered:3", "pt"],
        "higgs2_reco_jet2_eta": ["JetGoodFromHiggsOrdered:3", "eta"],
        "higgs2_reco_jet2_phi": ["JetGoodFromHiggsOrdered:3", "phi"],
        "higgs2_reco_jet2_mass": ["JetGoodFromHiggsOrdered:3", "mass"],
        "add_jet1pt_pt": ["add_jet1pt", "pt"],
        "add_jet1pt_eta": ["add_jet1pt", "eta"],
        "add_jet1pt_phi": ["add_jet1pt", "phi"],
        "add_jet1pt_mass": ["add_jet1pt", "mass"],
        "add_jet1pt_Higgs1_deta": ["add_jet1pt", "LeadingHiggs_dEta"],
        "add_jet1pt_Higgs1_dphi": ["add_jet1pt", "LeadingHiggs_dPhi"],
        "add_jet1pt_Higgs1_m": ["add_jet1pt", "LeadingHiggs_mass"],
        "add_jet1pt_Higgs2_deta": ["add_jet1pt", "SubLeadingHiggs_dEta"],
        "add_jet1pt_Higgs2_dphi": ["add_jet1pt", "SubLeadingHiggs_dPhi"],
        "add_jet1pt_Higgs2_m": ["add_jet1pt", "SubLeadingHiggs_mass"],
        "sigma_over_higgs1_reco_mass": ["events", "sigma_over_higgs1_reco_mass"],
        "sigma_over_higgs2_reco_mass": ["events", "sigma_over_higgs2_reco_mass"],
    }
)

sig_bkg_dnn_PaddedArctanhDeltaProb_input_variables = OrderedDict(
    {
        # "year": ["events", "year"],
        "Padded_Arctanh_Delta_pairing_probabilities": [
            "events",
            "Padded_Arctanh_Delta_pairing_probabilities",
        ],
        "HT": ["events", "HT"],
        "hh_vec_mass": ["HH", "mass"],
        "hh_vec_pt": ["HH", "pt"],
        "hh_vec_eta": ["HH", "eta"],
        "hh_vec_phi": ["HH", "phi"],
        "hh_vec_DeltaPhi": ["HH", "dPhi"],
        "hh_vec_DeltaEta": ["HH", "dEta"],
        "hh_vec_DeltaR": ["HH", "dR"],
        "hh_CosThetaStar_CS": ["HH", "Costhetastar_CS"],
        "higgs1_reco_pt": ["HiggsLeading", "pt"],
        "higgs1_reco_eta": ["HiggsLeading", "eta"],
        "higgs1_reco_phi": ["HiggsLeading", "phi"],
        "higgs1_reco_mass": ["HiggsLeading", "mass"],
        "higgs2_reco_pt": ["HiggsSubLeading", "pt"],
        "higgs2_reco_eta": ["HiggsSubLeading", "eta"],
        "higgs2_reco_phi": ["HiggsSubLeading", "phi"],
        "higgs2_reco_mass": ["HiggsSubLeading", "mass"],
        "higgs1_DeltaPhijj": ["HiggsLeading", "dPhi"],
        "higgs2_DeltaPhijj": ["HiggsSubLeading", "dPhi"],
        "higgs1_DeltaEtajj": ["HiggsLeading", "dEta"],
        "higgs2_DeltaEtajj": ["HiggsSubLeading", "dEta"],
        "minDeltaR_Higgjj": ["events", "dR_min"],
        "maxDeltaR_Higgjj": ["events", "dR_max"],
        "higgs1_helicityCosTheta": ["HiggsLeading", "helicityCosTheta"],
        "higgs2_helicityCosTheta": ["HiggsSubLeading", "helicityCosTheta"],
        "higgs1_reco_jet1_pt": ["JetGoodFromHiggsOrdered:0", "pt"],
        "higgs1_reco_jet1_eta": ["JetGoodFromHiggsOrdered:0", "eta"],
        "higgs1_reco_jet1_phi": ["JetGoodFromHiggsOrdered:0", "phi"],
        "higgs1_reco_jet1_mass": ["JetGoodFromHiggsOrdered:0", "mass"],
        "higgs1_reco_jet2_pt": ["JetGoodFromHiggsOrdered:1", "pt"],
        "higgs1_reco_jet2_eta": ["JetGoodFromHiggsOrdered:1", "eta"],
        "higgs1_reco_jet2_phi": ["JetGoodFromHiggsOrdered:1", "phi"],
        "higgs1_reco_jet2_mass": ["JetGoodFromHiggsOrdered:1", "mass"],
        "higgs2_reco_jet1_pt": ["JetGoodFromHiggsOrdered:2", "pt"],
        "higgs2_reco_jet1_eta": ["JetGoodFromHiggsOrdered:2", "eta"],
        "higgs2_reco_jet1_phi": ["JetGoodFromHiggsOrdered:2", "phi"],
        "higgs2_reco_jet1_mass": ["JetGoodFromHiggsOrdered:2", "mass"],
        "higgs2_reco_jet2_pt": ["JetGoodFromHiggsOrdered:3", "pt"],
        "higgs2_reco_jet2_eta": ["JetGoodFromHiggsOrdered:3", "eta"],
        "higgs2_reco_jet2_phi": ["JetGoodFromHiggsOrdered:3", "phi"],
        "higgs2_reco_jet2_mass": ["JetGoodFromHiggsOrdered:3", "mass"],
        "add_jet1pt_pt": ["add_jet1pt", "pt"],
        "add_jet1pt_eta": ["add_jet1pt", "eta"],
        "add_jet1pt_phi": ["add_jet1pt", "phi"],
        "add_jet1pt_mass": ["add_jet1pt", "mass"],
        "add_jet1pt_Higgs1_deta": ["add_jet1pt", "LeadingHiggs_dEta"],
        "add_jet1pt_Higgs1_dphi": ["add_jet1pt", "LeadingHiggs_dPhi"],
        "add_jet1pt_Higgs1_m": ["add_jet1pt", "LeadingHiggs_mass"],
        "add_jet1pt_Higgs2_deta": ["add_jet1pt", "SubLeadingHiggs_dEta"],
        "add_jet1pt_Higgs2_dphi": ["add_jet1pt", "SubLeadingHiggs_dPhi"],
        "add_jet1pt_Higgs2_m": ["add_jet1pt", "SubLeadingHiggs_mass"],
        "sigma_over_higgs1_reco_mass": ["events", "sigma_over_higgs1_reco_mass"],
        "sigma_over_higgs2_reco_mass": ["events", "sigma_over_higgs2_reco_mass"],
    }
)

sig_bkg_dnn_BkgReweightingVariables_input_variables = OrderedDict(
    {
        "higgs1_reco_pt": ["HiggsLeading", "pt"],
        "higgs1_reco_eta": ["HiggsLeading", "eta"],
        "higgs1_reco_phi": ["HiggsLeading", "phi"],
        "higgs1_reco_mass": ["HiggsLeading", "mass"],
        "higgs2_reco_pt": ["HiggsSubLeading", "pt"],
        "higgs2_reco_eta": ["HiggsSubLeading", "eta"],
        "higgs2_reco_phi": ["HiggsSubLeading", "phi"],
        "higgs2_reco_mass": ["HiggsSubLeading", "mass"],
        "HT": ["events", "HT"],
        "higgs1_DeltaRjj": ["HiggsLeading", "dR"],
        "higgs2_DeltaRjj": ["HiggsSubLeading", "dR"],
        "minDeltaR_Higgjj": ["events", "dR_min"],
        "maxDeltaR_Higgjj": ["events", "dR_max"],
        "higgs1_helicityCosTheta": ["HiggsLeading", "helicityCosTheta"],
        "higgs2_helicityCosTheta": ["HiggsSubLeading", "helicityCosTheta"],
        "hh_CosThetaStar_CS": ["HH", "Costhetastar_CS"],
        "hh_vec_mass": ["HH", "mass"],
        "hh_vec_pt": ["HH", "pt"],
        "hh_vec_eta": ["HH", "eta"],
        "hh_vec_DeltaR": ["HH", "dR"],
        "hh_vec_DeltaPhi": ["HH", "dPhi"],
        "hh_vec_DeltaEta": ["HH", "dEta"],
        "higgs1_reco_jet1_pt": ["JetGoodFromHiggsOrdered:0", "pt"],
        "higgs1_reco_jet1_eta": ["JetGoodFromHiggsOrdered:0", "eta"],
        "higgs1_reco_jet1_phi": ["JetGoodFromHiggsOrdered:0", "phi"],
        "higgs1_reco_jet1_mass": ["JetGoodFromHiggsOrdered:0", "mass"],
        "higgs1_reco_jet2_pt": ["JetGoodFromHiggsOrdered:1", "pt"],
        "higgs1_reco_jet2_eta": ["JetGoodFromHiggsOrdered:1", "eta"],
        "higgs1_reco_jet2_phi": ["JetGoodFromHiggsOrdered:1", "phi"],
        "higgs1_reco_jet2_mass": ["JetGoodFromHiggsOrdered:1", "mass"],
        "higgs2_reco_jet1_pt": ["JetGoodFromHiggsOrdered:2", "pt"],
        "higgs2_reco_jet1_eta": ["JetGoodFromHiggsOrdered:2", "eta"],
        "higgs2_reco_jet1_phi": ["JetGoodFromHiggsOrdered:2", "phi"],
        "higgs2_reco_jet1_mass": ["JetGoodFromHiggsOrdered:2", "mass"],
        "higgs2_reco_jet2_pt": ["JetGoodFromHiggsOrdered:3", "pt"],
        "higgs2_reco_jet2_eta": ["JetGoodFromHiggsOrdered:3", "eta"],
        "higgs2_reco_jet2_phi": ["JetGoodFromHiggsOrdered:3", "phi"],
        "higgs2_reco_jet2_mass": ["JetGoodFromHiggsOrdered:3", "mass"],
        "add_jet1pt_pt": ["add_jet1pt", "pt"],
        "add_jet1pt_eta": ["add_jet1pt", "eta"],
        "add_jet1pt_phi": ["add_jet1pt", "phi"],
        "add_jet1pt_mass": ["add_jet1pt", "mass"],
        "sigma_over_higgs1_reco_mass": ["events", "sigma_over_higgs1_reco_mass"],
        "sigma_over_higgs2_reco_mass": ["events", "sigma_over_higgs2_reco_mass"],
    }
)
#############
bkg_morphing_dnn_input_variables_mixeddata = OrderedDict(
    {
        # "era": ["events", "era"],
        "Delta_pairing_probabilities": ["events", "Delta_pairing_probabilities"],
        # "Delta_pairing_probabilities_best_worst": ["events", "Delta_pairing_probabilities_best_worst"],
        "higgs1_reco_pt": ["HiggsLeading", "pt"],
        "higgs1_reco_eta": ["HiggsLeading", "eta"],
        "higgs1_reco_phi": ["HiggsLeading", "phi"],
        "higgs1_reco_mass": ["HiggsLeading", "mass"],
        "higgs2_reco_pt": ["HiggsSubLeading", "pt"],
        "higgs2_reco_eta": ["HiggsSubLeading", "eta"],
        "higgs2_reco_phi": ["HiggsSubLeading", "phi"],
        "higgs2_reco_mass": ["HiggsSubLeading", "mass"],
        "HT": ["events", "HT"],
        "higgs1_DeltaRjj": ["HiggsLeading", "dR"],
        "higgs2_DeltaRjj": ["HiggsSubLeading", "dR"],
        "minDeltaR_Higgjj": ["events", "dR_min"],
        "maxDeltaR_Higgjj": ["events", "dR_max"],
        "higgs1_helicityCosTheta": ["HiggsLeading", "helicityCosTheta"],
        "higgs2_helicityCosTheta": ["HiggsSubLeading", "helicityCosTheta"],
        "hh_CosThetaStar_CS": ["HH", "Costhetastar_CS"],
        "hh_vec_mass": ["HH", "mass"],
        "hh_vec_pt": ["HH", "pt"],
        "hh_vec_eta": ["HH", "eta"],
        "hh_vec_DeltaR": ["HH", "dR"],
        "hh_vec_DeltaPhi": ["HH", "dPhi"],
        "hh_vec_DeltaEta": ["HH", "dEta"],
        "higgs1_reco_jet1_pt": ["JetGoodFromHiggsOrdered5Jets:0", "pt"],
        "higgs1_reco_jet1_eta": ["JetGoodFromHiggsOrdered5Jets:0", "eta"],
        "higgs1_reco_jet1_phi": ["JetGoodFromHiggsOrdered5Jets:0", "phi"],
        "higgs1_reco_jet1_mass": ["JetGoodFromHiggsOrdered5Jets:0", "mass"],
        "higgs1_reco_jet1_btag": ["JetGoodFromHiggsOrdered5Jets:0", "btagPNetB_5wp"],
        "higgs1_reco_jet2_pt": ["JetGoodFromHiggsOrdered5Jets:1", "pt"],
        "higgs1_reco_jet2_eta": ["JetGoodFromHiggsOrdered5Jets:1", "eta"],
        "higgs1_reco_jet2_phi": ["JetGoodFromHiggsOrdered5Jets:1", "phi"],
        "higgs1_reco_jet2_mass": ["JetGoodFromHiggsOrdered5Jets:1", "mass"],
        "higgs1_reco_jet2_btag": ["JetGoodFromHiggsOrdered5Jets:1", "btagPNetB_5wp"],
        "higgs2_reco_jet1_pt": ["JetGoodFromHiggsOrdered5Jets:2", "pt"],
        "higgs2_reco_jet1_eta": ["JetGoodFromHiggsOrdered5Jets:2", "eta"],
        "higgs2_reco_jet1_phi": ["JetGoodFromHiggsOrdered5Jets:2", "phi"],
        "higgs2_reco_jet1_mass": ["JetGoodFromHiggsOrdered5Jets:2", "mass"],
        "higgs2_reco_jet1_btag": ["JetGoodFromHiggsOrdered5Jets:2", "btagPNetB_5wp"],
        "higgs2_reco_jet2_pt": ["JetGoodFromHiggsOrdered5Jets:3", "pt"],
        "higgs2_reco_jet2_eta": ["JetGoodFromHiggsOrdered5Jets:3", "eta"],
        "higgs2_reco_jet2_phi": ["JetGoodFromHiggsOrdered5Jets:3", "phi"],
        "higgs2_reco_jet2_mass": ["JetGoodFromHiggsOrdered5Jets:3", "mass"],
        "higgs2_reco_jet2_btag": ["JetGoodFromHiggsOrdered5Jets:3", "btagPNetB_5wp"],
        "add_jet1pt_pt": ["JetGoodFromHiggsOrdered5Jets:4", "pt"],
        "add_jet1pt_eta": ["JetGoodFromHiggsOrdered5Jets:4", "eta"],
        "add_jet1pt_phi": ["JetGoodFromHiggsOrdered5Jets:4", "phi"],
        "add_jet1pt_mass": ["JetGoodFromHiggsOrdered5Jets:4", "mass"],
        "add_jet1pt_btag": ["JetGoodFromHiggsOrdered5Jets:4", "btagPNetB_5wp"],
        "sigma_over_higgs1_reco_mass": ["events", "sigma_over_higgs1_reco_mass"],
        "sigma_over_higgs2_reco_mass": ["events", "sigma_over_higgs2_reco_mass"],
    }
)
bkg_morphing_dnn_input_variables_mixeddata_bestworst_only = OrderedDict(
    {
        # "era": ["events", "era"],
        # "Delta_pairing_probabilities": ["events", "Delta_pairing_probabilities"],
        "Delta_pairing_probabilities_best_worst": ["events", "Delta_pairing_probabilities_best_worst"],
        "higgs1_reco_pt": ["HiggsLeading", "pt"],
        "higgs1_reco_eta": ["HiggsLeading", "eta"],
        "higgs1_reco_phi": ["HiggsLeading", "phi"],
        "higgs1_reco_mass": ["HiggsLeading", "mass"],
        "higgs2_reco_pt": ["HiggsSubLeading", "pt"],
        "higgs2_reco_eta": ["HiggsSubLeading", "eta"],
        "higgs2_reco_phi": ["HiggsSubLeading", "phi"],
        "higgs2_reco_mass": ["HiggsSubLeading", "mass"],
        "HT": ["events", "HT"],
        "higgs1_DeltaRjj": ["HiggsLeading", "dR"],
        "higgs2_DeltaRjj": ["HiggsSubLeading", "dR"],
        "minDeltaR_Higgjj": ["events", "dR_min"],
        "maxDeltaR_Higgjj": ["events", "dR_max"],
        "higgs1_helicityCosTheta": ["HiggsLeading", "helicityCosTheta"],
        "higgs2_helicityCosTheta": ["HiggsSubLeading", "helicityCosTheta"],
        "hh_CosThetaStar_CS": ["HH", "Costhetastar_CS"],
        "hh_vec_mass": ["HH", "mass"],
        "hh_vec_pt": ["HH", "pt"],
        "hh_vec_eta": ["HH", "eta"],
        "hh_vec_DeltaR": ["HH", "dR"],
        "hh_vec_DeltaPhi": ["HH", "dPhi"],
        "hh_vec_DeltaEta": ["HH", "dEta"],
        "higgs1_reco_jet1_pt": ["JetGoodFromHiggsOrdered5Jets:0", "pt"],
        "higgs1_reco_jet1_eta": ["JetGoodFromHiggsOrdered5Jets:0", "eta"],
        "higgs1_reco_jet1_phi": ["JetGoodFromHiggsOrdered5Jets:0", "phi"],
        "higgs1_reco_jet1_mass": ["JetGoodFromHiggsOrdered5Jets:0", "mass"],
        "higgs1_reco_jet1_btag": ["JetGoodFromHiggsOrdered5Jets:0", "btagPNetB_5wp"],
        "higgs1_reco_jet2_pt": ["JetGoodFromHiggsOrdered5Jets:1", "pt"],
        "higgs1_reco_jet2_eta": ["JetGoodFromHiggsOrdered5Jets:1", "eta"],
        "higgs1_reco_jet2_phi": ["JetGoodFromHiggsOrdered5Jets:1", "phi"],
        "higgs1_reco_jet2_mass": ["JetGoodFromHiggsOrdered5Jets:1", "mass"],
        "higgs1_reco_jet2_btag": ["JetGoodFromHiggsOrdered5Jets:1", "btagPNetB_5wp"],
        "higgs2_reco_jet1_pt": ["JetGoodFromHiggsOrdered5Jets:2", "pt"],
        "higgs2_reco_jet1_eta": ["JetGoodFromHiggsOrdered5Jets:2", "eta"],
        "higgs2_reco_jet1_phi": ["JetGoodFromHiggsOrdered5Jets:2", "phi"],
        "higgs2_reco_jet1_mass": ["JetGoodFromHiggsOrdered5Jets:2", "mass"],
        "higgs2_reco_jet1_btag": ["JetGoodFromHiggsOrdered5Jets:2", "btagPNetB_5wp"],
        "higgs2_reco_jet2_pt": ["JetGoodFromHiggsOrdered5Jets:3", "pt"],
        "higgs2_reco_jet2_eta": ["JetGoodFromHiggsOrdered5Jets:3", "eta"],
        "higgs2_reco_jet2_phi": ["JetGoodFromHiggsOrdered5Jets:3", "phi"],
        "higgs2_reco_jet2_mass": ["JetGoodFromHiggsOrdered5Jets:3", "mass"],
        "higgs2_reco_jet2_btag": ["JetGoodFromHiggsOrdered5Jets:3", "btagPNetB_5wp"],
        "add_jet1pt_pt": ["JetGoodFromHiggsOrdered5Jets:4", "pt"],
        "add_jet1pt_eta": ["JetGoodFromHiggsOrdered5Jets:4", "eta"],
        "add_jet1pt_phi": ["JetGoodFromHiggsOrdered5Jets:4", "phi"],
        "add_jet1pt_mass": ["JetGoodFromHiggsOrdered5Jets:4", "mass"],
        "add_jet1pt_btag": ["JetGoodFromHiggsOrdered5Jets:4", "btagPNetB_5wp"],
        "sigma_over_higgs1_reco_mass": ["events", "sigma_over_higgs1_reco_mass"],
        "sigma_over_higgs2_reco_mass": ["events", "sigma_over_higgs2_reco_mass"],
    }
)
bkg_morphing_dnn_input_variables_mixeddata_bestworst = OrderedDict(
    {
        # "era": ["events", "era"],
        "Delta_pairing_probabilities": ["events", "Delta_pairing_probabilities"],
        "Delta_pairing_probabilities_best_worst": ["events", "Delta_pairing_probabilities_best_worst"],
        "higgs1_reco_pt": ["HiggsLeading", "pt"],
        "higgs1_reco_eta": ["HiggsLeading", "eta"],
        "higgs1_reco_phi": ["HiggsLeading", "phi"],
        "higgs1_reco_mass": ["HiggsLeading", "mass"],
        "higgs2_reco_pt": ["HiggsSubLeading", "pt"],
        "higgs2_reco_eta": ["HiggsSubLeading", "eta"],
        "higgs2_reco_phi": ["HiggsSubLeading", "phi"],
        "higgs2_reco_mass": ["HiggsSubLeading", "mass"],
        "HT": ["events", "HT"],
        "higgs1_DeltaRjj": ["HiggsLeading", "dR"],
        "higgs2_DeltaRjj": ["HiggsSubLeading", "dR"],
        "minDeltaR_Higgjj": ["events", "dR_min"],
        "maxDeltaR_Higgjj": ["events", "dR_max"],
        "higgs1_helicityCosTheta": ["HiggsLeading", "helicityCosTheta"],
        "higgs2_helicityCosTheta": ["HiggsSubLeading", "helicityCosTheta"],
        "hh_CosThetaStar_CS": ["HH", "Costhetastar_CS"],
        "hh_vec_mass": ["HH", "mass"],
        "hh_vec_pt": ["HH", "pt"],
        "hh_vec_eta": ["HH", "eta"],
        "hh_vec_DeltaR": ["HH", "dR"],
        "hh_vec_DeltaPhi": ["HH", "dPhi"],
        "hh_vec_DeltaEta": ["HH", "dEta"],
        "higgs1_reco_jet1_pt": ["JetGoodFromHiggsOrdered5Jets:0", "pt"],
        "higgs1_reco_jet1_eta": ["JetGoodFromHiggsOrdered5Jets:0", "eta"],
        "higgs1_reco_jet1_phi": ["JetGoodFromHiggsOrdered5Jets:0", "phi"],
        "higgs1_reco_jet1_mass": ["JetGoodFromHiggsOrdered5Jets:0", "mass"],
        "higgs1_reco_jet1_btag": ["JetGoodFromHiggsOrdered5Jets:0", "btagPNetB_5wp"],
        "higgs1_reco_jet2_pt": ["JetGoodFromHiggsOrdered5Jets:1", "pt"],
        "higgs1_reco_jet2_eta": ["JetGoodFromHiggsOrdered5Jets:1", "eta"],
        "higgs1_reco_jet2_phi": ["JetGoodFromHiggsOrdered5Jets:1", "phi"],
        "higgs1_reco_jet2_mass": ["JetGoodFromHiggsOrdered5Jets:1", "mass"],
        "higgs1_reco_jet2_btag": ["JetGoodFromHiggsOrdered5Jets:1", "btagPNetB_5wp"],
        "higgs2_reco_jet1_pt": ["JetGoodFromHiggsOrdered5Jets:2", "pt"],
        "higgs2_reco_jet1_eta": ["JetGoodFromHiggsOrdered5Jets:2", "eta"],
        "higgs2_reco_jet1_phi": ["JetGoodFromHiggsOrdered5Jets:2", "phi"],
        "higgs2_reco_jet1_mass": ["JetGoodFromHiggsOrdered5Jets:2", "mass"],
        "higgs2_reco_jet1_btag": ["JetGoodFromHiggsOrdered5Jets:2", "btagPNetB_5wp"],
        "higgs2_reco_jet2_pt": ["JetGoodFromHiggsOrdered5Jets:3", "pt"],
        "higgs2_reco_jet2_eta": ["JetGoodFromHiggsOrdered5Jets:3", "eta"],
        "higgs2_reco_jet2_phi": ["JetGoodFromHiggsOrdered5Jets:3", "phi"],
        "higgs2_reco_jet2_mass": ["JetGoodFromHiggsOrdered5Jets:3", "mass"],
        "higgs2_reco_jet2_btag": ["JetGoodFromHiggsOrdered5Jets:3", "btagPNetB_5wp"],
        "add_jet1pt_pt": ["JetGoodFromHiggsOrdered5Jets:4", "pt"],
        "add_jet1pt_eta": ["JetGoodFromHiggsOrdered5Jets:4", "eta"],
        "add_jet1pt_phi": ["JetGoodFromHiggsOrdered5Jets:4", "phi"],
        "add_jet1pt_mass": ["JetGoodFromHiggsOrdered5Jets:4", "mass"],
        "add_jet1pt_btag": ["JetGoodFromHiggsOrdered5Jets:4", "btagPNetB_5wp"],
        "sigma_over_higgs1_reco_mass": ["events", "sigma_over_higgs1_reco_mass"],
        "sigma_over_higgs2_reco_mass": ["events", "sigma_over_higgs2_reco_mass"],
    }
)
sig_bkg_dnn_input_variables_spanet_mixeddata = OrderedDict(
    {
        "sequential": {
            # "jet_btag": ["JetGoodFromHiggsOrdered5Jets", "btagPNetB_5wp"],
            "jet_eta": ["JetGoodFromHiggsOrdered5Jets", "eta", "norm"],
            "jet_log_mass": ["JetGoodFromHiggsOrdered5Jets", "mass", "log_norm"],
            "jet_phi": ["JetGoodFromHiggsOrdered5Jets", "phi", "norm"],
            "jet_log_pt": ["JetGoodFromHiggsOrdered5Jets", "pt", "log_norm"],
            # "jet_higgs_prov": ["JetGoodFromHiggsOrdered5Jets", "higgs_provenance"]
            },
        "global": {
            # "Delta_pairing_probabilities": ["events", "Delta_pairing_probabilities"],
            "HT": ["events", "HT", "log_norm"],
            "maxDeltaR_Higgjj": ["events", "dR_max"],
            "minDeltaR_Higgjj": ["events", "dR_min"],
            "higgs1_reco_dR": ["HiggsLeading", "dR"],
            "higgs1_reco_eta": ["HiggsLeading", "eta"],
            "higgs1_helicityCosTheta": ["HiggsLeading", "helicityCosTheta"],
            "higgs1_reco_phi": ["HiggsLeading", "phi"],
            "higgs1_reco_mass": ["HiggsLeading", "mass", "log_norm"],
            "higgs1_reco_pt": ["HiggsLeading", "pt", "log_norm"],
            "higgs2_reco_dR": ["HiggsSubLeading", "dR"],
            "higgs2_reco_eta": ["HiggsSubLeading", "eta"],
            "higgs2_helicityCosTheta": ["HiggsSubLeading", "helicityCosTheta"],
            "higgs2_reco_phi": ["HiggsSubLeading", "phi"],
            "higgs2_reco_mass": ["HiggsSubLeading", "mass", "log_norm"],
            "higgs2_reco_pt": ["HiggsSubLeading", "pt", "log_norm"],
            "hh_CosThetaStar_CS": ["HH", "Costhetastar_CS"],
            "hh_vec_DeltaEta": ["HH", "dEta"],
            "hh_vec_DeltaR": ["HH", "dR"],
            "hh_vec_eta": ["HH", "eta", "norm"],
            "hh_vec_mass": ["HH", "mass", "log_norm"],
            "hh_vec_phi": ["HH", "phi"],
            "hh_vec_pt": ["HH", "pt", "log_norm"],
            }
    }
)
sig_bkg_dnn_input_variables_spanet_mixeddata_btag = OrderedDict(
    {
        "sequential": {
            "jet_btag": ["JetGoodFromHiggsOrdered5Jets", "btagPNetB_5wp"],
            "jet_eta": ["JetGoodFromHiggsOrdered5Jets", "eta", "norm"],
            "jet_log_mass": ["JetGoodFromHiggsOrdered5Jets", "mass", "log_norm"],
            "jet_phi": ["JetGoodFromHiggsOrdered5Jets", "phi", "norm"],
            "jet_log_pt": ["JetGoodFromHiggsOrdered5Jets", "pt", "log_norm"],
            },
        "global": {
            # "Delta_pairing_probabilities": ["events", "Delta_pairing_probabilities"],
            "HT": ["events", "HT", "log_norm"],
            "maxDeltaR_Higgjj": ["events", "dR_max"],
            "minDeltaR_Higgjj": ["events", "dR_min"],
            "higgs1_reco_dR": ["HiggsLeading", "dR"],
            "higgs1_reco_eta": ["HiggsLeading", "eta"],
            "higgs1_helicityCosTheta": ["HiggsLeading", "helicityCosTheta"],
            "higgs1_reco_phi": ["HiggsLeading", "phi"],
            "higgs1_reco_mass": ["HiggsLeading", "mass", "log_norm"],
            "higgs1_reco_pt": ["HiggsLeading", "pt", "log_norm"],
            "higgs2_reco_dR": ["HiggsSubLeading", "dR"],
            "higgs2_reco_eta": ["HiggsSubLeading", "eta"],
            "higgs2_helicityCosTheta": ["HiggsSubLeading", "helicityCosTheta"],
            "higgs2_reco_phi": ["HiggsSubLeading", "phi"],
            "higgs2_reco_mass": ["HiggsSubLeading", "mass", "log_norm"],
            "higgs2_reco_pt": ["HiggsSubLeading", "pt", "log_norm"],
            "hh_CosThetaStar_CS": ["HH", "Costhetastar_CS"],
            "hh_vec_DeltaEta": ["HH", "dEta"],
            "hh_vec_DeltaR": ["HH", "dR"],
            "hh_vec_eta": ["HH", "eta", "norm"],
            "hh_vec_mass": ["HH", "mass", "log_norm"],
            "hh_vec_phi": ["HH", "phi"],
            "hh_vec_pt": ["HH", "pt", "log_norm"],
            }
    }
)
sig_bkg_dnn_input_variables_spanet_mixeddata_pd = OrderedDict(
    {
        "sequential": {
            # "jet_btag": ["JetGoodFromHiggsOrdered5Jets", "btagPNetB_5wp"],
            "jet_eta": ["JetGoodFromHiggsOrdered5Jets", "eta", "norm"],
            "jet_log_mass": ["JetGoodFromHiggsOrdered5Jets", "mass", "log_norm"],
            "jet_phi": ["JetGoodFromHiggsOrdered5Jets", "phi", "norm"],
            "jet_log_pt": ["JetGoodFromHiggsOrdered5Jets", "pt", "log_norm"],
            },
        "global": {
            "Delta_pairing_probabilities": ["events", "Delta_pairing_probabilities"],
            "HT": ["events", "HT", "log_norm"],
            "maxDeltaR_Higgjj": ["events", "dR_max"],
            "minDeltaR_Higgjj": ["events", "dR_min"],
            "higgs1_reco_dR": ["HiggsLeading", "dR"],
            "higgs1_reco_eta": ["HiggsLeading", "eta"],
            "higgs1_helicityCosTheta": ["HiggsLeading", "helicityCosTheta"],
            "higgs1_reco_phi": ["HiggsLeading", "phi"],
            "higgs1_reco_mass": ["HiggsLeading", "mass", "log_norm"],
            "higgs1_reco_pt": ["HiggsLeading", "pt", "log_norm"],
            "higgs2_reco_dR": ["HiggsSubLeading", "dR"],
            "higgs2_reco_eta": ["HiggsSubLeading", "eta"],
            "higgs2_helicityCosTheta": ["HiggsSubLeading", "helicityCosTheta"],
            "higgs2_reco_phi": ["HiggsSubLeading", "phi"],
            "higgs2_reco_mass": ["HiggsSubLeading", "mass", "log_norm"],
            "higgs2_reco_pt": ["HiggsSubLeading", "pt", "log_norm"],
            "hh_CosThetaStar_CS": ["HH", "Costhetastar_CS"],
            "hh_vec_DeltaEta": ["HH", "dEta"],
            "hh_vec_DeltaR": ["HH", "dR"],
            "hh_vec_eta": ["HH", "eta", "norm"],
            "hh_vec_mass": ["HH", "mass", "log_norm"],
            "hh_vec_phi": ["HH", "phi"],
            "hh_vec_pt": ["HH", "pt", "log_norm"],
            }
    }
)
sig_bkg_dnn_input_variables_spanet_mixeddata_btag_pd = OrderedDict(
    {
        "sequential": {
            "jet_btag": ["JetGoodFromHiggsOrdered5Jets", "btagPNetB_5wp"],
            "jet_eta": ["JetGoodFromHiggsOrdered5Jets", "eta", "norm"],
            "jet_log_mass": ["JetGoodFromHiggsOrdered5Jets", "mass", "log_norm"],
            "jet_phi": ["JetGoodFromHiggsOrdered5Jets", "phi", "norm"],
            "jet_log_pt": ["JetGoodFromHiggsOrdered5Jets", "pt", "log_norm"],
            },
        "global": {
            "Delta_pairing_probabilities": ["events", "Delta_pairing_probabilities"],
            "HT": ["events", "HT", "log_norm"],
            "maxDeltaR_Higgjj": ["events", "dR_max"],
            "minDeltaR_Higgjj": ["events", "dR_min"],
            "higgs1_reco_dR": ["HiggsLeading", "dR"],
            "higgs1_reco_eta": ["HiggsLeading", "eta"],
            "higgs1_helicityCosTheta": ["HiggsLeading", "helicityCosTheta"],
            "higgs1_reco_phi": ["HiggsLeading", "phi"],
            "higgs1_reco_mass": ["HiggsLeading", "mass", "log_norm"],
            "higgs1_reco_pt": ["HiggsLeading", "pt", "log_norm"],
            "higgs2_reco_dR": ["HiggsSubLeading", "dR"],
            "higgs2_reco_eta": ["HiggsSubLeading", "eta"],
            "higgs2_helicityCosTheta": ["HiggsSubLeading", "helicityCosTheta"],
            "higgs2_reco_phi": ["HiggsSubLeading", "phi"],
            "higgs2_reco_mass": ["HiggsSubLeading", "mass", "log_norm"],
            "higgs2_reco_pt": ["HiggsSubLeading", "pt", "log_norm"],
            "hh_CosThetaStar_CS": ["HH", "Costhetastar_CS"],
            "hh_vec_DeltaEta": ["HH", "dEta"],
            "hh_vec_DeltaR": ["HH", "dR"],
            "hh_vec_eta": ["HH", "eta", "norm"],
            "hh_vec_mass": ["HH", "mass", "log_norm"],
            "hh_vec_phi": ["HH", "phi"],
            "hh_vec_pt": ["HH", "pt", "log_norm"],
            }
    }
)


sig_bkg_boosted_dnn_input_variables = OrderedDict(
    {
        # "vbf_cand_jets_pt": ["JetGoodVBFCandidates", "pt"],
        # "vbf_cand_jets_eta": ["JetGoodVBFCandidates", "eta"],
        # "vbf_cand_jets_phi": ["JetGoodVBFCandidates", "phi"],
        # "vbf_cand_jets_mass": ["JetGoodVBFCandidates", "mass"],
        "vbf_cand_jets_pt": ["JetGoodVBF", "pt"],
        "vbf_cand_jets_eta": ["JetGoodVBF", "eta"],
        "vbf_cand_jets_phi": ["JetGoodVBF", "phi"],
        "vbf_cand_jets_mass": ["JetGoodVBF", "mass"],
        "era": ["events", "era"],
        "HT": ["events", "HT"],
        "dijet_dEta": ["events", "dEta", "norm"],
        "higgs1_reco_pt": ["HiggsLeading", "pt"],
        "higgs1_reco_eta": ["HiggsLeading", "eta"],
        "higgs1_reco_phi": ["HiggsLeading", "phi"],
        "higgs1_reco_mass": ["HiggsLeading", "mass"],
        "higgs1_centrality": ["HiggsLeading", "centrality"],
        "higgs1_btagBB_wp": ["HiggsLeading", "btagBB_3wp"],
        # "higgs1_btagBB": ["HiggsLeading", "btagBB"],
        "higgs2_reco_pt": ["HiggsSubLeading", "pt"],
        "higgs2_reco_eta": ["HiggsSubLeading", "eta"],
        "higgs2_reco_phi": ["HiggsSubLeading", "phi"],
        "higgs2_reco_mass": ["HiggsSubLeading", "mass"],
        "higgs2_centrality": ["HiggsSubLeading", "centrality"],
        "higgs2_btagBB_wp": ["HiggsSubLeading", "btagBB_3wp"],
        # "higgs2_btagBB": ["HiggsSubLeading", "btagBB"],
        "higgs1_DeltaR_Hj": ["HiggsLeading", "dR_Hjet_min"],
        "higgs1_mass_Hj": ["HiggsLeading", "m_Hjet_min_dR"],
        "higgs2_DeltaR_Hj": ["HiggsSubLeading", "dR_Hjet_min"],
        "higgs2_mass_Hj": ["HiggsSubLeading", "m_Hjet_min_dR"],
        "hh_CosThetaStar_CS": ["HH", "Costhetastar_CS"],
        "hh_vec_mass": ["HH", "mass"],
        "hh_vec_pt": ["HH", "pt"],
        "hh_vec_eta": ["HH", "eta"],
        "hh_vec_phi": ["HH", "phi"],
        "hh_vec_DeltaR": ["HH", "dR"],
        "hh_vec_DeltaPhi": ["HH", "dPhi"],
        "hh_vec_DeltaEta": ["HH", "dEta"],
        "dijet_LeadingJet_pt": ["LeadingVBFJet", "pt"],
        "dijet_LeadingJet_eta": ["LeadingVBFJet", "eta"],
        "dijet_LeadingJet_phi": ["LeadingVBFJet", "phi"],
        "dijet_LeadingJet_mass": ["LeadingVBFJet", "mass"],
        "dijet_SubLeadingJet_pt": ["SubLeadingVBFJet", "pt"],
        "dijet_SubLeadingJet_eta": ["SubLeadingVBFJet", "eta"],
        "dijet_SubLeadingJet_phi": ["SubLeadingVBFJet", "phi"],
        "dijet_SubLeadingJet_mass": ["SubLeadingVBFJet", "mass"],
        "met_et": ["PuppiMET", "sumEt"],
    }
)

if __name__ == "__main__":
    # print the difference between the two dictionaries
    def print_dict_diff(dict1, dict2):
        for key in dict1:
            if key not in dict2:
                print(f"Key {key} is missing in the second dictionary")
            elif dict1[key] != dict2[key]:
                print(f"Key {key} has different values: {dict1[key]} vs {dict2[key]}")
        for key in dict2:
            if key not in dict1:
                print(f"Key {key} is missing in the first dictionary")

    # Call the function to print the differences
    print(
        "Differences between bkg_morphing_dnn_input_variables and bkg_morphing_dnn_input_variables_altOrder:"
    )
    print_dict_diff(bkg_morphing_dnn_input_variables, sig_bkg_dnn_input_variables)
