from collections import OrderedDict

#### Background Morphing Variables ####

bkg_morphing_dnn_input_variables = OrderedDict(
    {
        "era": ["events", "era"],
        "higgs1_reco_pt": ["HiggsLeading", "pt"],
        "higgs1_reco_eta": ["HiggsLeading", "eta"],
        "higgs1_reco_phi": ["HiggsLeading", "phi"],
        "higgs1_reco_mass": ["HiggsLeading", "mass"],
        "higgs2_reco_pt": ["HiggsSubLeading", "pt"],
        "higgs2_reco_eta": ["HiggsSubLeading", "eta"],
        "higgs2_reco_phi": ["HiggsSubLeading", "phi"],
        "higgs2_reco_mass": ["HiggsSubLeading", "mass"],
        "HT": ["events", "HT"],
        "higgs1_DeltaRjj": ["HiggsLeading", "dR"],
        "higgs2_DeltaRjj": ["HiggsSubLeading", "dR"],
        "minDeltaR_Higgjj": ["events", "dR_min"],
        "maxDeltaR_Higgjj": ["events", "dR_max"],
        "higgs1_helicityCosTheta": ["HiggsLeading", "helicityCosTheta"],
        "higgs2_helicityCosTheta": ["HiggsSubLeading", "helicityCosTheta"],
        "hh_CosThetaStar_CS": ["HH", "Costhetastar_CS"],
        "hh_vec_mass": ["HH", "mass"],
        "hh_vec_pt": ["HH", "pt"],
        "hh_vec_eta": ["HH", "eta"],
        "hh_vec_DeltaR": ["HH", "dR"],
        "hh_vec_DeltaPhi": ["HH", "dPhi"],
        "hh_vec_DeltaEta": ["HH", "dEta"],
        "higgs1_reco_jet1_pt": ["JetGoodFromHiggsOrdered:0", "pt"],
        "higgs1_reco_jet1_eta": ["JetGoodFromHiggsOrdered:0", "eta"],
        "higgs1_reco_jet1_phi": ["JetGoodFromHiggsOrdered:0", "phi"],
        "higgs1_reco_jet1_mass": ["JetGoodFromHiggsOrdered:0", "mass"],
        "higgs1_reco_jet2_pt": ["JetGoodFromHiggsOrdered:1", "pt"],
        "higgs1_reco_jet2_eta": ["JetGoodFromHiggsOrdered:1", "eta"],
        "higgs1_reco_jet2_phi": ["JetGoodFromHiggsOrdered:1", "phi"],
        "higgs1_reco_jet2_mass": ["JetGoodFromHiggsOrdered:1", "mass"],
        "higgs2_reco_jet1_pt": ["JetGoodFromHiggsOrdered:2", "pt"],
        "higgs2_reco_jet1_eta": ["JetGoodFromHiggsOrdered:2", "eta"],
        "higgs2_reco_jet1_phi": ["JetGoodFromHiggsOrdered:2", "phi"],
        "higgs2_reco_jet1_mass": ["JetGoodFromHiggsOrdered:2", "mass"],
        "higgs2_reco_jet2_pt": ["JetGoodFromHiggsOrdered:3", "pt"],
        "higgs2_reco_jet2_eta": ["JetGoodFromHiggsOrdered:3", "eta"],
        "higgs2_reco_jet2_phi": ["JetGoodFromHiggsOrdered:3", "phi"],
        "higgs2_reco_jet2_mass": ["JetGoodFromHiggsOrdered:3", "mass"],
        "add_jet1pt_pt": ["add_jet1pt", "pt"],
        "add_jet1pt_eta": ["add_jet1pt", "eta"],
        "add_jet1pt_phi": ["add_jet1pt", "phi"],
        "add_jet1pt_mass": ["add_jet1pt", "mass"],
        "sigma_over_higgs1_reco_mass": ["events", "sigma_over_higgs1_reco_mass"],
        "sigma_over_higgs2_reco_mass": ["events", "sigma_over_higgs2_reco_mass"],
    }
)

bkg_morphing_dnn_DeltaProb_input_variables = OrderedDict(
    {
        "era": ["events", "era"],
        "Delta_pairing_probabilities": ["events", "Delta_pairing_probabilities"],
        "higgs1_reco_pt": ["HiggsLeading", "pt"],
        "higgs1_reco_eta": ["HiggsLeading", "eta"],
        "higgs1_reco_phi": ["HiggsLeading", "phi"],
        "higgs1_reco_mass": ["HiggsLeading", "mass"],
        "higgs2_reco_pt": ["HiggsSubLeading", "pt"],
        "higgs2_reco_eta": ["HiggsSubLeading", "eta"],
        "higgs2_reco_phi": ["HiggsSubLeading", "phi"],
        "higgs2_reco_mass": ["HiggsSubLeading", "mass"],
        "HT": ["events", "HT"],
        "higgs1_DeltaRjj": ["HiggsLeading", "dR"],
        "higgs2_DeltaRjj": ["HiggsSubLeading", "dR"],
        "minDeltaR_Higgjj": ["events", "dR_min"],
        "maxDeltaR_Higgjj": ["events", "dR_max"],
        "higgs1_helicityCosTheta": ["HiggsLeading", "helicityCosTheta"],
        "higgs2_helicityCosTheta": ["HiggsSubLeading", "helicityCosTheta"],
        "hh_CosThetaStar_CS": ["HH", "Costhetastar_CS"],
        "hh_vec_mass": ["HH", "mass"],
        "hh_vec_pt": ["HH", "pt"],
        "hh_vec_eta": ["HH", "eta"],
        "hh_vec_DeltaR": ["HH", "dR"],
        "hh_vec_DeltaPhi": ["HH", "dPhi"],
        "hh_vec_DeltaEta": ["HH", "dEta"],
        "higgs1_reco_jet1_pt": ["JetGoodFromHiggsOrdered:0", "pt"],
        "higgs1_reco_jet1_eta": ["JetGoodFromHiggsOrdered:0", "eta"],
        "higgs1_reco_jet1_phi": ["JetGoodFromHiggsOrdered:0", "phi"],
        "higgs1_reco_jet1_mass": ["JetGoodFromHiggsOrdered:0", "mass"],
        "higgs1_reco_jet2_pt": ["JetGoodFromHiggsOrdered:1", "pt"],
        "higgs1_reco_jet2_eta": ["JetGoodFromHiggsOrdered:1", "eta"],
        "higgs1_reco_jet2_phi": ["JetGoodFromHiggsOrdered:1", "phi"],
        "higgs1_reco_jet2_mass": ["JetGoodFromHiggsOrdered:1", "mass"],
        "higgs2_reco_jet1_pt": ["JetGoodFromHiggsOrdered:2", "pt"],
        "higgs2_reco_jet1_eta": ["JetGoodFromHiggsOrdered:2", "eta"],
        "higgs2_reco_jet1_phi": ["JetGoodFromHiggsOrdered:2", "phi"],
        "higgs2_reco_jet1_mass": ["JetGoodFromHiggsOrdered:2", "mass"],
        "higgs2_reco_jet2_pt": ["JetGoodFromHiggsOrdered:3", "pt"],
        "higgs2_reco_jet2_eta": ["JetGoodFromHiggsOrdered:3", "eta"],
        "higgs2_reco_jet2_phi": ["JetGoodFromHiggsOrdered:3", "phi"],
        "higgs2_reco_jet2_mass": ["JetGoodFromHiggsOrdered:3", "mass"],
        "add_jet1pt_pt": ["add_jet1pt", "pt"],
        "add_jet1pt_eta": ["add_jet1pt", "eta"],
        "add_jet1pt_phi": ["add_jet1pt", "phi"],
        "add_jet1pt_mass": ["add_jet1pt", "mass"],
        "sigma_over_higgs1_reco_mass": ["events", "sigma_over_higgs1_reco_mass"],
        "sigma_over_higgs2_reco_mass": ["events", "sigma_over_higgs2_reco_mass"],
    }
)

bkg_morphing_dnn_ArctanhDeltaProb_input_variables = OrderedDict(
    {
        "era": ["events", "era"],
        "Arctanh_Delta_pairing_probabilities": [
            "events",
            "Arctanh_Delta_pairing_probabilities",
        ],
        "higgs1_reco_pt": ["HiggsLeading", "pt"],
        "higgs1_reco_eta": ["HiggsLeading", "eta"],
        "higgs1_reco_phi": ["HiggsLeading", "phi"],
        "higgs1_reco_mass": ["HiggsLeading", "mass"],
        "higgs2_reco_pt": ["HiggsSubLeading", "pt"],
        "higgs2_reco_eta": ["HiggsSubLeading", "eta"],
        "higgs2_reco_phi": ["HiggsSubLeading", "phi"],
        "higgs2_reco_mass": ["HiggsSubLeading", "mass"],
        "HT": ["events", "HT"],
        "higgs1_DeltaRjj": ["HiggsLeading", "dR"],
        "higgs2_DeltaRjj": ["HiggsSubLeading", "dR"],
        "minDeltaR_Higgjj": ["events", "dR_min"],
        "maxDeltaR_Higgjj": ["events", "dR_max"],
        "higgs1_helicityCosTheta": ["HiggsLeading", "helicityCosTheta"],
        "higgs2_helicityCosTheta": ["HiggsSubLeading", "helicityCosTheta"],
        "hh_CosThetaStar_CS": ["HH", "Costhetastar_CS"],
        "hh_vec_mass": ["HH", "mass"],
        "hh_vec_pt": ["HH", "pt"],
        "hh_vec_eta": ["HH", "eta"],
        "hh_vec_DeltaR": ["HH", "dR"],
        "hh_vec_DeltaPhi": ["HH", "dPhi"],
        "hh_vec_DeltaEta": ["HH", "dEta"],
        "higgs1_reco_jet1_pt": ["JetGoodFromHiggsOrdered:0", "pt"],
        "higgs1_reco_jet1_eta": ["JetGoodFromHiggsOrdered:0", "eta"],
        "higgs1_reco_jet1_phi": ["JetGoodFromHiggsOrdered:0", "phi"],
        "higgs1_reco_jet1_mass": ["JetGoodFromHiggsOrdered:0", "mass"],
        "higgs1_reco_jet2_pt": ["JetGoodFromHiggsOrdered:1", "pt"],
        "higgs1_reco_jet2_eta": ["JetGoodFromHiggsOrdered:1", "eta"],
        "higgs1_reco_jet2_phi": ["JetGoodFromHiggsOrdered:1", "phi"],
        "higgs1_reco_jet2_mass": ["JetGoodFromHiggsOrdered:1", "mass"],
        "higgs2_reco_jet1_pt": ["JetGoodFromHiggsOrdered:2", "pt"],
        "higgs2_reco_jet1_eta": ["JetGoodFromHiggsOrdered:2", "eta"],
        "higgs2_reco_jet1_phi": ["JetGoodFromHiggsOrdered:2", "phi"],
        "higgs2_reco_jet1_mass": ["JetGoodFromHiggsOrdered:2", "mass"],
        "higgs2_reco_jet2_pt": ["JetGoodFromHiggsOrdered:3", "pt"],
        "higgs2_reco_jet2_eta": ["JetGoodFromHiggsOrdered:3", "eta"],
        "higgs2_reco_jet2_phi": ["JetGoodFromHiggsOrdered:3", "phi"],
        "higgs2_reco_jet2_mass": ["JetGoodFromHiggsOrdered:3", "mass"],
        "add_jet1pt_pt": ["add_jet1pt", "pt"],
        "add_jet1pt_eta": ["add_jet1pt", "eta"],
        "add_jet1pt_phi": ["add_jet1pt", "phi"],
        "add_jet1pt_mass": ["add_jet1pt", "mass"],
        "sigma_over_higgs1_reco_mass": ["events", "sigma_over_higgs1_reco_mass"],
        "sigma_over_higgs2_reco_mass": ["events", "sigma_over_higgs2_reco_mass"],
    }
)

bkg_morphing_dnn_BinnedArctanhDeltaProb_input_variables = OrderedDict(
    {
        "era": ["events", "era"],
        "Binned_Arctanh_Delta_pairing_probabilities": [
            "events",
            "Binned_Arctanh_Delta_pairing_probabilities",
        ],
        "higgs1_reco_pt": ["HiggsLeading", "pt"],
        "higgs1_reco_eta": ["HiggsLeading", "eta"],
        "higgs1_reco_phi": ["HiggsLeading", "phi"],
        "higgs1_reco_mass": ["HiggsLeading", "mass"],
        "higgs2_reco_pt": ["HiggsSubLeading", "pt"],
        "higgs2_reco_eta": ["HiggsSubLeading", "eta"],
        "higgs2_reco_phi": ["HiggsSubLeading", "phi"],
        "higgs2_reco_mass": ["HiggsSubLeading", "mass"],
        "HT": ["events", "HT"],
        "higgs1_DeltaRjj": ["HiggsLeading", "dR"],
        "higgs2_DeltaRjj": ["HiggsSubLeading", "dR"],
        "minDeltaR_Higgjj": ["events", "dR_min"],
        "maxDeltaR_Higgjj": ["events", "dR_max"],
        "higgs1_helicityCosTheta": ["HiggsLeading", "helicityCosTheta"],
        "higgs2_helicityCosTheta": ["HiggsSubLeading", "helicityCosTheta"],
        "hh_CosThetaStar_CS": ["HH", "Costhetastar_CS"],
        "hh_vec_mass": ["HH", "mass"],
        "hh_vec_pt": ["HH", "pt"],
        "hh_vec_eta": ["HH", "eta"],
        "hh_vec_DeltaR": ["HH", "dR"],
        "hh_vec_DeltaPhi": ["HH", "dPhi"],
        "hh_vec_DeltaEta": ["HH", "dEta"],
        "higgs1_reco_jet1_pt": ["JetGoodFromHiggsOrdered:0", "pt"],
        "higgs1_reco_jet1_eta": ["JetGoodFromHiggsOrdered:0", "eta"],
        "higgs1_reco_jet1_phi": ["JetGoodFromHiggsOrdered:0", "phi"],
        "higgs1_reco_jet1_mass": ["JetGoodFromHiggsOrdered:0", "mass"],
        "higgs1_reco_jet2_pt": ["JetGoodFromHiggsOrdered:1", "pt"],
        "higgs1_reco_jet2_eta": ["JetGoodFromHiggsOrdered:1", "eta"],
        "higgs1_reco_jet2_phi": ["JetGoodFromHiggsOrdered:1", "phi"],
        "higgs1_reco_jet2_mass": ["JetGoodFromHiggsOrdered:1", "mass"],
        "higgs2_reco_jet1_pt": ["JetGoodFromHiggsOrdered:2", "pt"],
        "higgs2_reco_jet1_eta": ["JetGoodFromHiggsOrdered:2", "eta"],
        "higgs2_reco_jet1_phi": ["JetGoodFromHiggsOrdered:2", "phi"],
        "higgs2_reco_jet1_mass": ["JetGoodFromHiggsOrdered:2", "mass"],
        "higgs2_reco_jet2_pt": ["JetGoodFromHiggsOrdered:3", "pt"],
        "higgs2_reco_jet2_eta": ["JetGoodFromHiggsOrdered:3", "eta"],
        "higgs2_reco_jet2_phi": ["JetGoodFromHiggsOrdered:3", "phi"],
        "higgs2_reco_jet2_mass": ["JetGoodFromHiggsOrdered:3", "mass"],
        "add_jet1pt_pt": ["add_jet1pt", "pt"],
        "add_jet1pt_eta": ["add_jet1pt", "eta"],
        "add_jet1pt_phi": ["add_jet1pt", "phi"],
        "add_jet1pt_mass": ["add_jet1pt", "mass"],
        "sigma_over_higgs1_reco_mass": ["events", "sigma_over_higgs1_reco_mass"],
        "sigma_over_higgs2_reco_mass": ["events", "sigma_over_higgs2_reco_mass"],
    }
)

bkg_morphing_dnn_PaddedArctanhDeltaProb_input_variables = OrderedDict(
    {
        "era": ["events", "era"],
        "Padded_Arctanh_Delta_pairing_probabilities": [
            "events",
            "Padded_Arctanh_Delta_pairing_probabilities",
        ],
        "higgs1_reco_pt": ["HiggsLeading", "pt"],
        "higgs1_reco_eta": ["HiggsLeading", "eta"],
        "higgs1_reco_phi": ["HiggsLeading", "phi"],
        "higgs1_reco_mass": ["HiggsLeading", "mass"],
        "higgs2_reco_pt": ["HiggsSubLeading", "pt"],
        "higgs2_reco_eta": ["HiggsSubLeading", "eta"],
        "higgs2_reco_phi": ["HiggsSubLeading", "phi"],
        "higgs2_reco_mass": ["HiggsSubLeading", "mass"],
        "HT": ["events", "HT"],
        "higgs1_DeltaRjj": ["HiggsLeading", "dR"],
        "higgs2_DeltaRjj": ["HiggsSubLeading", "dR"],
        "minDeltaR_Higgjj": ["events", "dR_min"],
        "maxDeltaR_Higgjj": ["events", "dR_max"],
        "higgs1_helicityCosTheta": ["HiggsLeading", "helicityCosTheta"],
        "higgs2_helicityCosTheta": ["HiggsSubLeading", "helicityCosTheta"],
        "hh_CosThetaStar_CS": ["HH", "Costhetastar_CS"],
        "hh_vec_mass": ["HH", "mass"],
        "hh_vec_pt": ["HH", "pt"],
        "hh_vec_eta": ["HH", "eta"],
        "hh_vec_DeltaR": ["HH", "dR"],
        "hh_vec_DeltaPhi": ["HH", "dPhi"],
        "hh_vec_DeltaEta": ["HH", "dEta"],
        "higgs1_reco_jet1_pt": ["JetGoodFromHiggsOrdered:0", "pt"],
        "higgs1_reco_jet1_eta": ["JetGoodFromHiggsOrdered:0", "eta"],
        "higgs1_reco_jet1_phi": ["JetGoodFromHiggsOrdered:0", "phi"],
        "higgs1_reco_jet1_mass": ["JetGoodFromHiggsOrdered:0", "mass"],
        "higgs1_reco_jet2_pt": ["JetGoodFromHiggsOrdered:1", "pt"],
        "higgs1_reco_jet2_eta": ["JetGoodFromHiggsOrdered:1", "eta"],
        "higgs1_reco_jet2_phi": ["JetGoodFromHiggsOrdered:1", "phi"],
        "higgs1_reco_jet2_mass": ["JetGoodFromHiggsOrdered:1", "mass"],
        "higgs2_reco_jet1_pt": ["JetGoodFromHiggsOrdered:2", "pt"],
        "higgs2_reco_jet1_eta": ["JetGoodFromHiggsOrdered:2", "eta"],
        "higgs2_reco_jet1_phi": ["JetGoodFromHiggsOrdered:2", "phi"],
        "higgs2_reco_jet1_mass": ["JetGoodFromHiggsOrdered:2", "mass"],
        "higgs2_reco_jet2_pt": ["JetGoodFromHiggsOrdered:3", "pt"],
        "higgs2_reco_jet2_eta": ["JetGoodFromHiggsOrdered:3", "eta"],
        "higgs2_reco_jet2_phi": ["JetGoodFromHiggsOrdered:3", "phi"],
        "higgs2_reco_jet2_mass": ["JetGoodFromHiggsOrdered:3", "mass"],
        "add_jet1pt_pt": ["add_jet1pt", "pt"],
        "add_jet1pt_eta": ["add_jet1pt", "eta"],
        "add_jet1pt_phi": ["add_jet1pt", "phi"],
        "add_jet1pt_mass": ["add_jet1pt", "mass"],
        "sigma_over_higgs1_reco_mass": ["events", "sigma_over_higgs1_reco_mass"],
        "sigma_over_higgs2_reco_mass": ["events", "sigma_over_higgs2_reco_mass"],
    }
)

bkg_morphing_dnn_input_variables_altOrder = OrderedDict(
    {
        "era": ["events", "era"],
        "higgs1_reco_pt": ["HiggsLeading", "pt"],
        "higgs1_reco_eta": ["HiggsLeading", "eta"],
        "higgs1_reco_phi": ["HiggsLeading", "phi"],
        "higgs1_reco_mass": ["HiggsLeading", "mass"],
        "higgs2_reco_pt": ["HiggsSubLeading", "pt"],
        "higgs2_reco_eta": ["HiggsSubLeading", "eta"],
        "higgs2_reco_phi": ["HiggsSubLeading", "phi"],
        "higgs2_reco_mass": ["HiggsSubLeading", "mass"],
        "HT": ["events", "HT"],
        "higgs1_DeltaRjj": ["HiggsLeading", "dR"],
        "higgs2_DeltaRjj": ["HiggsSubLeading", "dR"],
        "minDeltaR_Higgjj": ["events", "dR_min"],
        "maxDeltaR_Higgjj": ["events", "dR_max"],
        "higgs1_helicityCosTheta": ["HiggsLeading", "helicityCosTheta"],
        "higgs2_helicityCosTheta": ["HiggsSubLeading", "helicityCosTheta"],
        "hh_CosThetaStar_CS": ["HH", "Costhetastar_CS"],
        "hh_vec_mass": ["HH", "mass"],
        "hh_vec_pt": ["HH", "pt"],
        "hh_vec_eta": ["HH", "eta"],
        "hh_vec_DeltaR": ["HH", "dR"],
        "hh_vec_DeltaPhi": ["HH", "dPhi"],
        "hh_vec_DeltaEta": ["HH", "dEta"],
        "higgs1_reco_jet1_pt": ["JetGoodFromHiggsOrdered:0", "pt"],
        "higgs1_reco_jet2_pt": ["JetGoodFromHiggsOrdered:1", "pt"],
        "higgs2_reco_jet1_pt": ["JetGoodFromHiggsOrdered:2", "pt"],
        "higgs2_reco_jet2_pt": ["JetGoodFromHiggsOrdered:3", "pt"],
        "higgs1_reco_jet1_eta": ["JetGoodFromHiggsOrdered:0", "eta"],
        "higgs1_reco_jet2_eta": ["JetGoodFromHiggsOrdered:1", "eta"],
        "higgs2_reco_jet1_eta": ["JetGoodFromHiggsOrdered:2", "eta"],
        "higgs2_reco_jet2_eta": ["JetGoodFromHiggsOrdered:3", "eta"],
        "higgs1_reco_jet1_phi": ["JetGoodFromHiggsOrdered:0", "phi"],
        "higgs1_reco_jet2_phi": ["JetGoodFromHiggsOrdered:1", "phi"],
        "higgs2_reco_jet1_phi": ["JetGoodFromHiggsOrdered:2", "phi"],
        "higgs2_reco_jet2_phi": ["JetGoodFromHiggsOrdered:3", "phi"],
        "higgs1_reco_jet1_mass": ["JetGoodFromHiggsOrdered:0", "mass"],
        "higgs1_reco_jet2_mass": ["JetGoodFromHiggsOrdered:1", "mass"],
        "higgs2_reco_jet1_mass": ["JetGoodFromHiggsOrdered:2", "mass"],
        "higgs2_reco_jet2_mass": ["JetGoodFromHiggsOrdered:3", "mass"],
        "add_jet1pt_pt": ["add_jet1pt", "pt"],
        "add_jet1pt_eta": ["add_jet1pt", "eta"],
        "add_jet1pt_phi": ["add_jet1pt", "phi"],
        "add_jet1pt_mass": ["add_jet1pt", "mass"],
        "sigma_over_higgs1_reco_mass": ["events", "sigma_over_higgs1_reco_mass"],
        "sigma_over_higgs2_reco_mass": ["events", "sigma_over_higgs2_reco_mass"],
    }
)


bkg_morphing_dnn_SigBkgVariables_input_variables = OrderedDict(
    {
        "era": ["events", "era"],
        "HT": ["events", "HT"],
        "hh_vec_mass": ["HH", "mass"],
        "hh_vec_pt": ["HH", "pt"],
        "hh_vec_eta": ["HH", "eta"],
        "hh_vec_phi": ["HH", "phi"],
        "hh_vec_DeltaPhi": ["HH", "dPhi"],
        "hh_vec_DeltaEta": ["HH", "dEta"],
        "hh_vec_DeltaR": ["HH", "dR"],
        "hh_CosThetaStar_CS": ["HH", "Costhetastar_CS"],
        "higgs1_reco_pt": ["HiggsLeading", "pt"],
        "higgs1_reco_eta": ["HiggsLeading", "eta"],
        "higgs1_reco_phi": ["HiggsLeading", "phi"],
        "higgs1_reco_mass": ["HiggsLeading", "mass"],
        "higgs2_reco_pt": ["HiggsSubLeading", "pt"],
        "higgs2_reco_eta": ["HiggsSubLeading", "eta"],
        "higgs2_reco_phi": ["HiggsSubLeading", "phi"],
        "higgs2_reco_mass": ["HiggsSubLeading", "mass"],
        "higgs1_DeltaPhijj": ["HiggsLeading", "dPhi"],
        "higgs2_DeltaPhijj": ["HiggsSubLeading", "dPhi"],
        "higgs1_DeltaEtajj": ["HiggsLeading", "dEta"],
        "higgs2_DeltaEtajj": ["HiggsSubLeading", "dEta"],
        "minDeltaR_Higgjj": ["events", "dR_min"],
        "maxDeltaR_Higgjj": ["events", "dR_max"],
        "higgs1_helicityCosTheta": ["HiggsLeading", "helicityCosTheta"],
        "higgs2_helicityCosTheta": ["HiggsSubLeading", "helicityCosTheta"],
        "higgs1_reco_jet1_pt": ["JetGoodFromHiggsOrdered:0", "pt"],
        "higgs1_reco_jet1_eta": ["JetGoodFromHiggsOrdered:0", "eta"],
        "higgs1_reco_jet1_phi": ["JetGoodFromHiggsOrdered:0", "phi"],
        "higgs1_reco_jet1_mass": ["JetGoodFromHiggsOrdered:0", "mass"],
        "higgs1_reco_jet2_pt": ["JetGoodFromHiggsOrdered:1", "pt"],
        "higgs1_reco_jet2_eta": ["JetGoodFromHiggsOrdered:1", "eta"],
        "higgs1_reco_jet2_phi": ["JetGoodFromHiggsOrdered:1", "phi"],
        "higgs1_reco_jet2_mass": ["JetGoodFromHiggsOrdered:1", "mass"],
        "higgs2_reco_jet1_pt": ["JetGoodFromHiggsOrdered:2", "pt"],
        "higgs2_reco_jet1_eta": ["JetGoodFromHiggsOrdered:2", "eta"],
        "higgs2_reco_jet1_phi": ["JetGoodFromHiggsOrdered:2", "phi"],
        "higgs2_reco_jet1_mass": ["JetGoodFromHiggsOrdered:2", "mass"],
        "higgs2_reco_jet2_pt": ["JetGoodFromHiggsOrdered:3", "pt"],
        "higgs2_reco_jet2_eta": ["JetGoodFromHiggsOrdered:3", "eta"],
        "higgs2_reco_jet2_phi": ["JetGoodFromHiggsOrdered:3", "phi"],
        "higgs2_reco_jet2_mass": ["JetGoodFromHiggsOrdered:3", "mass"],
        "add_jet1pt_pt": ["add_jet1pt", "pt"],
        "add_jet1pt_eta": ["add_jet1pt", "eta"],
        "add_jet1pt_phi": ["add_jet1pt", "phi"],
        "add_jet1pt_mass": ["add_jet1pt", "mass"],
        "add_jet1pt_Higgs1_deta": ["add_jet1pt", "LeadingHiggs_dEta"],
        "add_jet1pt_Higgs1_dphi": ["add_jet1pt", "LeadingHiggs_dPhi"],
        "add_jet1pt_Higgs1_m": ["add_jet1pt", "LeadingHiggs_mass"],
        "add_jet1pt_Higgs2_deta": ["add_jet1pt", "SubLeadingHiggs_dEta"],
        "add_jet1pt_Higgs2_dphi": ["add_jet1pt", "SubLeadingHiggs_dPhi"],
        "add_jet1pt_Higgs2_m": ["add_jet1pt", "SubLeadingHiggs_mass"],
        "sigma_over_higgs1_reco_mass": ["events", "sigma_over_higgs1_reco_mass"],
        "sigma_over_higgs2_reco_mass": ["events", "sigma_over_higgs2_reco_mass"],
    }
)


#### Signal VS Background Variables ####

sig_bkg_dnn_input_variables = OrderedDict(
    {
        # "year": ["events", "year"],
        "HT": ["events", "HT"],
        "hh_vec_mass": ["HH", "mass"],
        "hh_vec_pt": ["HH", "pt"],
        "hh_vec_eta": ["HH", "eta"],
        "hh_vec_phi": ["HH", "phi"],
        "hh_vec_DeltaPhi": ["HH", "dPhi"],
        "hh_vec_DeltaEta": ["HH", "dEta"],
        "hh_vec_DeltaR": ["HH", "dR"],
        "hh_CosThetaStar_CS": ["HH", "Costhetastar_CS"],
        "higgs1_reco_pt": ["HiggsLeading", "pt"],
        "higgs1_reco_eta": ["HiggsLeading", "eta"],
        "higgs1_reco_phi": ["HiggsLeading", "phi"],
        "higgs1_reco_mass": ["HiggsLeading", "mass"],
        "higgs2_reco_pt": ["HiggsSubLeading", "pt"],
        "higgs2_reco_eta": ["HiggsSubLeading", "eta"],
        "higgs2_reco_phi": ["HiggsSubLeading", "phi"],
        "higgs2_reco_mass": ["HiggsSubLeading", "mass"],
        "higgs1_DeltaPhijj": ["HiggsLeading", "dPhi"],
        "higgs2_DeltaPhijj": ["HiggsSubLeading", "dPhi"],
        "higgs1_DeltaEtajj": ["HiggsLeading", "dEta"],
        "higgs2_DeltaEtajj": ["HiggsSubLeading", "dEta"],
        "minDeltaR_Higgjj": ["events", "dR_min"],
        "maxDeltaR_Higgjj": ["events", "dR_max"],
        "higgs1_helicityCosTheta": ["HiggsLeading", "helicityCosTheta"],
        "higgs2_helicityCosTheta": ["HiggsSubLeading", "helicityCosTheta"],
        "higgs1_reco_jet1_pt": ["JetGoodFromHiggsOrdered:0", "pt"],
        "higgs1_reco_jet1_eta": ["JetGoodFromHiggsOrdered:0", "eta"],
        "higgs1_reco_jet1_phi": ["JetGoodFromHiggsOrdered:0", "phi"],
        "higgs1_reco_jet1_mass": ["JetGoodFromHiggsOrdered:0", "mass"],
        "higgs1_reco_jet2_pt": ["JetGoodFromHiggsOrdered:1", "pt"],
        "higgs1_reco_jet2_eta": ["JetGoodFromHiggsOrdered:1", "eta"],
        "higgs1_reco_jet2_phi": ["JetGoodFromHiggsOrdered:1", "phi"],
        "higgs1_reco_jet2_mass": ["JetGoodFromHiggsOrdered:1", "mass"],
        "higgs2_reco_jet1_pt": ["JetGoodFromHiggsOrdered:2", "pt"],
        "higgs2_reco_jet1_eta": ["JetGoodFromHiggsOrdered:2", "eta"],
        "higgs2_reco_jet1_phi": ["JetGoodFromHiggsOrdered:2", "phi"],
        "higgs2_reco_jet1_mass": ["JetGoodFromHiggsOrdered:2", "mass"],
        "higgs2_reco_jet2_pt": ["JetGoodFromHiggsOrdered:3", "pt"],
        "higgs2_reco_jet2_eta": ["JetGoodFromHiggsOrdered:3", "eta"],
        "higgs2_reco_jet2_phi": ["JetGoodFromHiggsOrdered:3", "phi"],
        "higgs2_reco_jet2_mass": ["JetGoodFromHiggsOrdered:3", "mass"],
        "add_jet1pt_pt": ["add_jet1pt", "pt"],
        "add_jet1pt_eta": ["add_jet1pt", "eta"],
        "add_jet1pt_phi": ["add_jet1pt", "phi"],
        "add_jet1pt_mass": ["add_jet1pt", "mass"],
        "add_jet1pt_Higgs1_deta": ["add_jet1pt", "LeadingHiggs_dEta"],
        "add_jet1pt_Higgs1_dphi": ["add_jet1pt", "LeadingHiggs_dPhi"],
        "add_jet1pt_Higgs1_m": ["add_jet1pt", "LeadingHiggs_mass"],
        "add_jet1pt_Higgs2_deta": ["add_jet1pt", "SubLeadingHiggs_dEta"],
        "add_jet1pt_Higgs2_dphi": ["add_jet1pt", "SubLeadingHiggs_dPhi"],
        "add_jet1pt_Higgs2_m": ["add_jet1pt", "SubLeadingHiggs_mass"],
        "sigma_over_higgs1_reco_mass": ["events", "sigma_over_higgs1_reco_mass"],
        "sigma_over_higgs2_reco_mass": ["events", "sigma_over_higgs2_reco_mass"],
    }
)
pairing_spanet_btagWP = OrderedDict(
    {
        "sequential": {
            "jet_log_pt": ["JetGood", "pt", "log_norm"],
            "jet_eta": ["JetGood", "eta", "norm"],
            "jet_phi": ["JetGood", "phi", "norm"],
            "jet_btag_wp": ["JetGood", "btagPNetB_wp"],
            },
        "global": {
            }
    }
)
pairing_spanet_btagWP5 = OrderedDict(
    {
        "sequential": {
            "jet_log_pt": ["JetGood", "pt", "log_norm"],
            "jet_eta": ["JetGood", "eta", "norm"],
            "jet_phi": ["JetGood", "phi", "norm"],
            "jet_btag_5wp": ["JetGood", "btagPNetB_5wp"],
            },
        "global": {
            }
    }
)
pairing_spanet_btagWP3 = OrderedDict(
    {
        "sequential": {
            "jet_log_pt": ["JetGood", "pt", "log_norm"],
            "jet_eta": ["JetGood", "eta", "norm"],
            "jet_phi": ["JetGood", "phi", "norm"],
            "jet_btag_3wp": ["JetGood", "btagPNetB_3wp"],
            },
        "global": {
            }
    }
)

pairing_spanet_btagDeltaWP5 = OrderedDict(
    {
        "sequential": {
            "jet_log_pt": ["JetGood", "pt", "log_norm"],
            "jet_eta": ["JetGood", "eta", "norm"],
            "jet_phi": ["JetGood", "phi", "norm"],
            "jet_btag_delta5wp": ["JetGood", "btagPNetB_delta5wp"],
            },
        "global": {
            }
    }
)

pairing_spanet_btag12_ratioSubLead = OrderedDict(
    {
        "sequential": {
            "jet_log_pt": ["JetGood", "pt", "log_norm"],
            "jet_eta": ["JetGood", "eta", "norm"],
            "jet_phi": ["JetGood", "phi", "norm"],
            "jet_btag12_ratioSubLead": ["JetGood", "btag12_ratioSubLead"],
            },
        "global": {
            }
    }
)

pairing_spanet_btag = OrderedDict(
    {
        "sequential": {
            "jet_log_pt": ["JetGood", "pt", "log_norm"],
            "jet_eta": ["JetGood", "eta", "norm"],
            "jet_phi": ["JetGood", "phi", "norm"],
            "jet_btag": ["JetGood", "btagPNetB"],
            },
        "global": {
            }
    }
)

pairing_spanet_btag_ratioAll = OrderedDict(
    {
        "sequential": {
            "jet_log_pt": ["JetGood", "pt", "log_norm"],
            "jet_eta": ["JetGood", "eta", "norm"],
            "jet_phi": ["JetGood", "phi", "norm"],
            "jet_btag_ratioAll": ["JetGood", "btag_ratioAll"],
            },
        "global": {
            }
    }
)

pairing_spanet_vbf_ggf_btagWP5 = OrderedDict(
    {
        "sequential": {
            "jet_log_pt": ["JetTotalSPANetPadded", "pt", "log_norm"],
            "jet_eta": ["JetTotalSPANetPadded", "eta", "norm"],
            "jet_phi": ["JetTotalSPANetPadded", "phi", "norm"],
            "jet_btag_5wp": ["JetTotalSPANetPadded", "btagPNetB_5wp"],
            },
        "global": {
            }
    }
)

sig_bkg_dnn_input_variables_spanet = OrderedDict(
    {
        "sequential": {
            "jet_log_pt": ["JetGoodFromHiggsOrdered", "pt", "log_norm"],
            "jet_eta": ["JetGoodFromHiggsOrdered", "eta", "norm"],
            "jet_phi": ["JetGoodFromHiggsOrdered", "phi", "norm"],
            "jet_log_mass": ["JetGoodFromHiggsOrdered", "mass", "log_norm"],
            },
        "global": {
            # "Arctanh_Delta_pairing_probabilities": ["events", "Arctanh_Delta_pairing_probabilities"],
            "maxDeltaR_Higgjj": ["events", "dR_max"],
            "minDeltaR_Higgjj": ["events", "dR_min"],
            "HT": ["events", "HT", "log_norm"],
            "higgs1_reco_pt": ["HiggsLeading", "pt", "log_norm"],
            "higgs1_reco_eta": ["HiggsLeading", "eta"],
            "higgs1_reco_phi": ["HiggsLeading", "phi"],
            "higgs1_reco_mass": ["HiggsLeading", "mass", "log_norm"],
            "higgs1_reco_dR": ["HiggsLeading", "dR"],
            "higgs1_helicityCosTheta": ["HiggsLeading", "helicityCosTheta"],
            "higgs2_reco_pt": ["HiggsSubLeading", "pt", "log_norm"],
            "higgs2_reco_eta": ["HiggsSubLeading", "eta"],
            "higgs2_reco_phi": ["HiggsSubLeading", "phi"],
            "higgs2_reco_mass": ["HiggsSubLeading", "mass", "log_norm"],
            "higgs2_reco_dR": ["HiggsSubLeading", "dR"],
            "higgs2_helicityCosTheta": ["HiggsSubLeading", "helicityCosTheta"],
            "hh_vec_pt": ["HH", "pt", "log_norm"],
            "hh_vec_eta": ["HH", "eta", "norm"],
            "hh_vec_phi": ["HH", "phi"],
            "hh_vec_mass": ["HH", "mass", "log_norm"],
            "hh_vec_DeltaR": ["HH", "dR"],
            "hh_vec_DeltaEta": ["HH", "dEta"],
            "hh_vec_DeltaPhi": ["HH", "dPhi"],
            }
    }
)

sig_bkg_dnn_DeltaProb_input_variables = OrderedDict(
    {
        # "year": ["events", "year"],
        "Delta_pairing_probabilities": ["events", "Delta_pairing_probabilities"],
        "HT": ["events", "HT"],
        "hh_vec_mass": ["HH", "mass"],
        "hh_vec_pt": ["HH", "pt"],
        "hh_vec_eta": ["HH", "eta"],
        "hh_vec_phi": ["HH", "phi"],
        "hh_vec_DeltaPhi": ["HH", "dPhi"],
        "hh_vec_DeltaEta": ["HH", "dEta"],
        "hh_vec_DeltaR": ["HH", "dR"],
        "hh_CosThetaStar_CS": ["HH", "Costhetastar_CS"],
        "higgs1_reco_pt": ["HiggsLeading", "pt"],
        "higgs1_reco_eta": ["HiggsLeading", "eta"],
        "higgs1_reco_phi": ["HiggsLeading", "phi"],
        "higgs1_reco_mass": ["HiggsLeading", "mass"],
        "higgs2_reco_pt": ["HiggsSubLeading", "pt"],
        "higgs2_reco_eta": ["HiggsSubLeading", "eta"],
        "higgs2_reco_phi": ["HiggsSubLeading", "phi"],
        "higgs2_reco_mass": ["HiggsSubLeading", "mass"],
        "higgs1_DeltaPhijj": ["HiggsLeading", "dPhi"],
        "higgs2_DeltaPhijj": ["HiggsSubLeading", "dPhi"],
        "higgs1_DeltaEtajj": ["HiggsLeading", "dEta"],
        "higgs2_DeltaEtajj": ["HiggsSubLeading", "dEta"],
        "minDeltaR_Higgjj": ["events", "dR_min"],
        "maxDeltaR_Higgjj": ["events", "dR_max"],
        "higgs1_helicityCosTheta": ["HiggsLeading", "helicityCosTheta"],
        "higgs2_helicityCosTheta": ["HiggsSubLeading", "helicityCosTheta"],
        "higgs1_reco_jet1_pt": ["JetGoodFromHiggsOrdered:0", "pt"],
        "higgs1_reco_jet1_eta": ["JetGoodFromHiggsOrdered:0", "eta"],
        "higgs1_reco_jet1_phi": ["JetGoodFromHiggsOrdered:0", "phi"],
        "higgs1_reco_jet1_mass": ["JetGoodFromHiggsOrdered:0", "mass"],
        "higgs1_reco_jet2_pt": ["JetGoodFromHiggsOrdered:1", "pt"],
        "higgs1_reco_jet2_eta": ["JetGoodFromHiggsOrdered:1", "eta"],
        "higgs1_reco_jet2_phi": ["JetGoodFromHiggsOrdered:1", "phi"],
        "higgs1_reco_jet2_mass": ["JetGoodFromHiggsOrdered:1", "mass"],
        "higgs2_reco_jet1_pt": ["JetGoodFromHiggsOrdered:2", "pt"],
        "higgs2_reco_jet1_eta": ["JetGoodFromHiggsOrdered:2", "eta"],
        "higgs2_reco_jet1_phi": ["JetGoodFromHiggsOrdered:2", "phi"],
        "higgs2_reco_jet1_mass": ["JetGoodFromHiggsOrdered:2", "mass"],
        "higgs2_reco_jet2_pt": ["JetGoodFromHiggsOrdered:3", "pt"],
        "higgs2_reco_jet2_eta": ["JetGoodFromHiggsOrdered:3", "eta"],
        "higgs2_reco_jet2_phi": ["JetGoodFromHiggsOrdered:3", "phi"],
        "higgs2_reco_jet2_mass": ["JetGoodFromHiggsOrdered:3", "mass"],
        "add_jet1pt_pt": ["add_jet1pt", "pt"],
        "add_jet1pt_eta": ["add_jet1pt", "eta"],
        "add_jet1pt_phi": ["add_jet1pt", "phi"],
        "add_jet1pt_mass": ["add_jet1pt", "mass"],
        "add_jet1pt_Higgs1_deta": ["add_jet1pt", "LeadingHiggs_dEta"],
        "add_jet1pt_Higgs1_dphi": ["add_jet1pt", "LeadingHiggs_dPhi"],
        "add_jet1pt_Higgs1_m": ["add_jet1pt", "LeadingHiggs_mass"],
        "add_jet1pt_Higgs2_deta": ["add_jet1pt", "SubLeadingHiggs_dEta"],
        "add_jet1pt_Higgs2_dphi": ["add_jet1pt", "SubLeadingHiggs_dPhi"],
        "add_jet1pt_Higgs2_m": ["add_jet1pt", "SubLeadingHiggs_mass"],
        "sigma_over_higgs1_reco_mass": ["events", "sigma_over_higgs1_reco_mass"],
        "sigma_over_higgs2_reco_mass": ["events", "sigma_over_higgs2_reco_mass"],
    }
)

sig_bkg_dnn_DeltaProb_input_variables_less_add_jet1pt_vars = OrderedDict(
    {
        # "year": ["events", "year"],
        "Delta_pairing_probabilities": ["events", "Delta_pairing_probabilities"],
        "HT": ["events", "HT"],
        "hh_vec_mass": ["HH", "mass"],
        "hh_vec_pt": ["HH", "pt"],
        "hh_vec_eta": ["HH", "eta"],
        "hh_vec_phi": ["HH", "phi"],
        "hh_vec_DeltaPhi": ["HH", "dPhi"],
        "hh_vec_DeltaEta": ["HH", "dEta"],
        "hh_vec_DeltaR": ["HH", "dR"],
        "hh_CosThetaStar_CS": ["HH", "Costhetastar_CS"],
        "higgs1_reco_pt": ["HiggsLeading", "pt"],
        "higgs1_reco_eta": ["HiggsLeading", "eta"],
        "higgs1_reco_phi": ["HiggsLeading", "phi"],
        "higgs1_reco_mass": ["HiggsLeading", "mass"],
        "higgs2_reco_pt": ["HiggsSubLeading", "pt"],
        "higgs2_reco_eta": ["HiggsSubLeading", "eta"],
        "higgs2_reco_phi": ["HiggsSubLeading", "phi"],
        "higgs2_reco_mass": ["HiggsSubLeading", "mass"],
        "higgs1_DeltaPhijj": ["HiggsLeading", "dPhi"],
        "higgs2_DeltaPhijj": ["HiggsSubLeading", "dPhi"],
        "higgs1_DeltaEtajj": ["HiggsLeading", "dEta"],
        "higgs2_DeltaEtajj": ["HiggsSubLeading", "dEta"],
        "minDeltaR_Higgjj": ["events", "dR_min"],
        "maxDeltaR_Higgjj": ["events", "dR_max"],
        "higgs1_helicityCosTheta": ["HiggsLeading", "helicityCosTheta"],
        "higgs2_helicityCosTheta": ["HiggsSubLeading", "helicityCosTheta"],
        "higgs1_reco_jet1_pt": ["JetGoodFromHiggsOrdered:0", "pt"],
        "higgs1_reco_jet1_eta": ["JetGoodFromHiggsOrdered:0", "eta"],
        "higgs1_reco_jet1_phi": ["JetGoodFromHiggsOrdered:0", "phi"],
        "higgs1_reco_jet1_mass": ["JetGoodFromHiggsOrdered:0", "mass"],
        "higgs1_reco_jet2_pt": ["JetGoodFromHiggsOrdered:1", "pt"],
        "higgs1_reco_jet2_eta": ["JetGoodFromHiggsOrdered:1", "eta"],
        "higgs1_reco_jet2_phi": ["JetGoodFromHiggsOrdered:1", "phi"],
        "higgs1_reco_jet2_mass": ["JetGoodFromHiggsOrdered:1", "mass"],
        "higgs2_reco_jet1_pt": ["JetGoodFromHiggsOrdered:2", "pt"],
        "higgs2_reco_jet1_eta": ["JetGoodFromHiggsOrdered:2", "eta"],
        "higgs2_reco_jet1_phi": ["JetGoodFromHiggsOrdered:2", "phi"],
        "higgs2_reco_jet1_mass": ["JetGoodFromHiggsOrdered:2", "mass"],
        "higgs2_reco_jet2_pt": ["JetGoodFromHiggsOrdered:3", "pt"],
        "higgs2_reco_jet2_eta": ["JetGoodFromHiggsOrdered:3", "eta"],
        "higgs2_reco_jet2_phi": ["JetGoodFromHiggsOrdered:3", "phi"],
        "higgs2_reco_jet2_mass": ["JetGoodFromHiggsOrdered:3", "mass"],
        "add_jet1pt_pt": ["add_jet1pt", "pt"],
        "add_jet1pt_eta": ["add_jet1pt", "eta"],
        "add_jet1pt_phi": ["add_jet1pt", "phi"],
        "add_jet1pt_mass": ["add_jet1pt", "mass"],
        #        "add_jet1pt_Higgs1_deta": ["add_jet1pt", "LeadingHiggs_dEta"],
        #        "add_jet1pt_Higgs1_dphi": ["add_jet1pt", "LeadingHiggs_dPhi"],
        #        "add_jet1pt_Higgs1_m": ["add_jet1pt", "LeadingHiggs_mass"],
        #        "add_jet1pt_Higgs2_deta": ["add_jet1pt", "SubLeadingHiggs_dEta"],
        #        "add_jet1pt_Higgs2_dphi": ["add_jet1pt", "SubLeadingHiggs_dPhi"],
        #        "add_jet1pt_Higgs2_m": ["add_jet1pt", "SubLeadingHiggs_mass"],
        "sigma_over_higgs1_reco_mass": ["events", "sigma_over_higgs1_reco_mass"],
        "sigma_over_higgs2_reco_mass": ["events", "sigma_over_higgs2_reco_mass"],
    }
)

sig_bkg_dnn_ArctanhDeltaProb_input_variables = OrderedDict(
    {
        # "year": ["events", "year"],
        "Arctanh_Delta_pairing_probabilities": [
            "events",
            "Arctanh_Delta_pairing_probabilities",
        ],
        "HT": ["events", "HT"],
        "hh_vec_mass": ["HH", "mass"],
        "hh_vec_pt": ["HH", "pt"],
        "hh_vec_eta": ["HH", "eta"],
        "hh_vec_phi": ["HH", "phi"],
        "hh_vec_DeltaPhi": ["HH", "dPhi"],
        "hh_vec_DeltaEta": ["HH", "dEta"],
        "hh_vec_DeltaR": ["HH", "dR"],
        "hh_CosThetaStar_CS": ["HH", "Costhetastar_CS"],
        "higgs1_reco_pt": ["HiggsLeading", "pt"],
        "higgs1_reco_eta": ["HiggsLeading", "eta"],
        "higgs1_reco_phi": ["HiggsLeading", "phi"],
        "higgs1_reco_mass": ["HiggsLeading", "mass"],
        "higgs2_reco_pt": ["HiggsSubLeading", "pt"],
        "higgs2_reco_eta": ["HiggsSubLeading", "eta"],
        "higgs2_reco_phi": ["HiggsSubLeading", "phi"],
        "higgs2_reco_mass": ["HiggsSubLeading", "mass"],
        "higgs1_DeltaPhijj": ["HiggsLeading", "dPhi"],
        "higgs2_DeltaPhijj": ["HiggsSubLeading", "dPhi"],
        "higgs1_DeltaEtajj": ["HiggsLeading", "dEta"],
        "higgs2_DeltaEtajj": ["HiggsSubLeading", "dEta"],
        "minDeltaR_Higgjj": ["events", "dR_min"],
        "maxDeltaR_Higgjj": ["events", "dR_max"],
        "higgs1_helicityCosTheta": ["HiggsLeading", "helicityCosTheta"],
        "higgs2_helicityCosTheta": ["HiggsSubLeading", "helicityCosTheta"],
        "higgs1_reco_jet1_pt": ["JetGoodFromHiggsOrdered:0", "pt"],
        "higgs1_reco_jet1_eta": ["JetGoodFromHiggsOrdered:0", "eta"],
        "higgs1_reco_jet1_phi": ["JetGoodFromHiggsOrdered:0", "phi"],
        "higgs1_reco_jet1_mass": ["JetGoodFromHiggsOrdered:0", "mass"],
        "higgs1_reco_jet2_pt": ["JetGoodFromHiggsOrdered:1", "pt"],
        "higgs1_reco_jet2_eta": ["JetGoodFromHiggsOrdered:1", "eta"],
        "higgs1_reco_jet2_phi": ["JetGoodFromHiggsOrdered:1", "phi"],
        "higgs1_reco_jet2_mass": ["JetGoodFromHiggsOrdered:1", "mass"],
        "higgs2_reco_jet1_pt": ["JetGoodFromHiggsOrdered:2", "pt"],
        "higgs2_reco_jet1_eta": ["JetGoodFromHiggsOrdered:2", "eta"],
        "higgs2_reco_jet1_phi": ["JetGoodFromHiggsOrdered:2", "phi"],
        "higgs2_reco_jet1_mass": ["JetGoodFromHiggsOrdered:2", "mass"],
        "higgs2_reco_jet2_pt": ["JetGoodFromHiggsOrdered:3", "pt"],
        "higgs2_reco_jet2_eta": ["JetGoodFromHiggsOrdered:3", "eta"],
        "higgs2_reco_jet2_phi": ["JetGoodFromHiggsOrdered:3", "phi"],
        "higgs2_reco_jet2_mass": ["JetGoodFromHiggsOrdered:3", "mass"],
        "add_jet1pt_pt": ["add_jet1pt", "pt"],
        "add_jet1pt_eta": ["add_jet1pt", "eta"],
        "add_jet1pt_phi": ["add_jet1pt", "phi"],
        "add_jet1pt_mass": ["add_jet1pt", "mass"],
        "add_jet1pt_Higgs1_deta": ["add_jet1pt", "LeadingHiggs_dEta"],
        "add_jet1pt_Higgs1_dphi": ["add_jet1pt", "LeadingHiggs_dPhi"],
        "add_jet1pt_Higgs1_m": ["add_jet1pt", "LeadingHiggs_mass"],
        "add_jet1pt_Higgs2_deta": ["add_jet1pt", "SubLeadingHiggs_dEta"],
        "add_jet1pt_Higgs2_dphi": ["add_jet1pt", "SubLeadingHiggs_dPhi"],
        "add_jet1pt_Higgs2_m": ["add_jet1pt", "SubLeadingHiggs_mass"],
        "sigma_over_higgs1_reco_mass": ["events", "sigma_over_higgs1_reco_mass"],
        "sigma_over_higgs2_reco_mass": ["events", "sigma_over_higgs2_reco_mass"],
    }
)

sig_bkg_dnn_ArctanhDeltaProb_input_variables_less_add_jet1pt_vars = OrderedDict(
    {
        # "year": ["events", "year"],
        "Arctanh_Delta_pairing_probabilities": [
            "events",
            "Arctanh_Delta_pairing_probabilities",
        ],
        "HT": ["events", "HT"],
        "hh_vec_mass": ["HH", "mass"],
        "hh_vec_pt": ["HH", "pt"],
        "hh_vec_eta": ["HH", "eta"],
        "hh_vec_phi": ["HH", "phi"],
        "hh_vec_DeltaPhi": ["HH", "dPhi"],
        "hh_vec_DeltaEta": ["HH", "dEta"],
        "hh_vec_DeltaR": ["HH", "dR"],
        "hh_CosThetaStar_CS": ["HH", "Costhetastar_CS"],
        "higgs1_reco_pt": ["HiggsLeading", "pt"],
        "higgs1_reco_eta": ["HiggsLeading", "eta"],
        "higgs1_reco_phi": ["HiggsLeading", "phi"],
        "higgs1_reco_mass": ["HiggsLeading", "mass"],
        "higgs2_reco_pt": ["HiggsSubLeading", "pt"],
        "higgs2_reco_eta": ["HiggsSubLeading", "eta"],
        "higgs2_reco_phi": ["HiggsSubLeading", "phi"],
        "higgs2_reco_mass": ["HiggsSubLeading", "mass"],
        "higgs1_DeltaPhijj": ["HiggsLeading", "dPhi"],
        "higgs2_DeltaPhijj": ["HiggsSubLeading", "dPhi"],
        "higgs1_DeltaEtajj": ["HiggsLeading", "dEta"],
        "higgs2_DeltaEtajj": ["HiggsSubLeading", "dEta"],
        "minDeltaR_Higgjj": ["events", "dR_min"],
        "maxDeltaR_Higgjj": ["events", "dR_max"],
        "higgs1_helicityCosTheta": ["HiggsLeading", "helicityCosTheta"],
        "higgs2_helicityCosTheta": ["HiggsSubLeading", "helicityCosTheta"],
        "higgs1_reco_jet1_pt": ["JetGoodFromHiggsOrdered:0", "pt"],
        "higgs1_reco_jet1_eta": ["JetGoodFromHiggsOrdered:0", "eta"],
        "higgs1_reco_jet1_phi": ["JetGoodFromHiggsOrdered:0", "phi"],
        "higgs1_reco_jet1_mass": ["JetGoodFromHiggsOrdered:0", "mass"],
        "higgs1_reco_jet2_pt": ["JetGoodFromHiggsOrdered:1", "pt"],
        "higgs1_reco_jet2_eta": ["JetGoodFromHiggsOrdered:1", "eta"],
        "higgs1_reco_jet2_phi": ["JetGoodFromHiggsOrdered:1", "phi"],
        "higgs1_reco_jet2_mass": ["JetGoodFromHiggsOrdered:1", "mass"],
        "higgs2_reco_jet1_pt": ["JetGoodFromHiggsOrdered:2", "pt"],
        "higgs2_reco_jet1_eta": ["JetGoodFromHiggsOrdered:2", "eta"],
        "higgs2_reco_jet1_phi": ["JetGoodFromHiggsOrdered:2", "phi"],
        "higgs2_reco_jet1_mass": ["JetGoodFromHiggsOrdered:2", "mass"],
        "higgs2_reco_jet2_pt": ["JetGoodFromHiggsOrdered:3", "pt"],
        "higgs2_reco_jet2_eta": ["JetGoodFromHiggsOrdered:3", "eta"],
        "higgs2_reco_jet2_phi": ["JetGoodFromHiggsOrdered:3", "phi"],
        "higgs2_reco_jet2_mass": ["JetGoodFromHiggsOrdered:3", "mass"],
        "add_jet1pt_pt": ["add_jet1pt", "pt"],
        "add_jet1pt_eta": ["add_jet1pt", "eta"],
        "add_jet1pt_phi": ["add_jet1pt", "phi"],
        "add_jet1pt_mass": ["add_jet1pt", "mass"],
        #        "add_jet1pt_Higgs1_deta": ["add_jet1pt", "LeadingHiggs_dEta"],
        #        "add_jet1pt_Higgs1_dphi": ["add_jet1pt", "LeadingHiggs_dPhi"],
        #        "add_jet1pt_Higgs1_m": ["add_jet1pt", "LeadingHiggs_mass"],
        #        "add_jet1pt_Higgs2_deta": ["add_jet1pt", "SubLeadingHiggs_dEta"],
        #        "add_jet1pt_Higgs2_dphi": ["add_jet1pt", "SubLeadingHiggs_dPhi"],
        #        "add_jet1pt_Higgs2_m": ["add_jet1pt", "SubLeadingHiggs_mass"],
        "sigma_over_higgs1_reco_mass": ["events", "sigma_over_higgs1_reco_mass"],
        "sigma_over_higgs2_reco_mass": ["events", "sigma_over_higgs2_reco_mass"],
    }
)

sig_bkg_dnn_BinnedArctanhDeltaProb_input_variables = OrderedDict(
    {
        # "year": ["events", "year"],
        "Binned_Arctanh_Delta_pairing_probabilities": [
            "events",
            "Binned_Arctanh_Delta_pairing_probabilities",
        ],
        "HT": ["events", "HT"],
        "hh_vec_mass": ["HH", "mass"],
        "hh_vec_pt": ["HH", "pt"],
        "hh_vec_eta": ["HH", "eta"],
        "hh_vec_phi": ["HH", "phi"],
        "hh_vec_DeltaPhi": ["HH", "dPhi"],
        "hh_vec_DeltaEta": ["HH", "dEta"],
        "hh_vec_DeltaR": ["HH", "dR"],
        "hh_CosThetaStar_CS": ["HH", "Costhetastar_CS"],
        "higgs1_reco_pt": ["HiggsLeading", "pt"],
        "higgs1_reco_eta": ["HiggsLeading", "eta"],
        "higgs1_reco_phi": ["HiggsLeading", "phi"],
        "higgs1_reco_mass": ["HiggsLeading", "mass"],
        "higgs2_reco_pt": ["HiggsSubLeading", "pt"],
        "higgs2_reco_eta": ["HiggsSubLeading", "eta"],
        "higgs2_reco_phi": ["HiggsSubLeading", "phi"],
        "higgs2_reco_mass": ["HiggsSubLeading", "mass"],
        "higgs1_DeltaPhijj": ["HiggsLeading", "dPhi"],
        "higgs2_DeltaPhijj": ["HiggsSubLeading", "dPhi"],
        "higgs1_DeltaEtajj": ["HiggsLeading", "dEta"],
        "higgs2_DeltaEtajj": ["HiggsSubLeading", "dEta"],
        "minDeltaR_Higgjj": ["events", "dR_min"],
        "maxDeltaR_Higgjj": ["events", "dR_max"],
        "higgs1_helicityCosTheta": ["HiggsLeading", "helicityCosTheta"],
        "higgs2_helicityCosTheta": ["HiggsSubLeading", "helicityCosTheta"],
        "higgs1_reco_jet1_pt": ["JetGoodFromHiggsOrdered:0", "pt"],
        "higgs1_reco_jet1_eta": ["JetGoodFromHiggsOrdered:0", "eta"],
        "higgs1_reco_jet1_phi": ["JetGoodFromHiggsOrdered:0", "phi"],
        "higgs1_reco_jet1_mass": ["JetGoodFromHiggsOrdered:0", "mass"],
        "higgs1_reco_jet2_pt": ["JetGoodFromHiggsOrdered:1", "pt"],
        "higgs1_reco_jet2_eta": ["JetGoodFromHiggsOrdered:1", "eta"],
        "higgs1_reco_jet2_phi": ["JetGoodFromHiggsOrdered:1", "phi"],
        "higgs1_reco_jet2_mass": ["JetGoodFromHiggsOrdered:1", "mass"],
        "higgs2_reco_jet1_pt": ["JetGoodFromHiggsOrdered:2", "pt"],
        "higgs2_reco_jet1_eta": ["JetGoodFromHiggsOrdered:2", "eta"],
        "higgs2_reco_jet1_phi": ["JetGoodFromHiggsOrdered:2", "phi"],
        "higgs2_reco_jet1_mass": ["JetGoodFromHiggsOrdered:2", "mass"],
        "higgs2_reco_jet2_pt": ["JetGoodFromHiggsOrdered:3", "pt"],
        "higgs2_reco_jet2_eta": ["JetGoodFromHiggsOrdered:3", "eta"],
        "higgs2_reco_jet2_phi": ["JetGoodFromHiggsOrdered:3", "phi"],
        "higgs2_reco_jet2_mass": ["JetGoodFromHiggsOrdered:3", "mass"],
        "add_jet1pt_pt": ["add_jet1pt", "pt"],
        "add_jet1pt_eta": ["add_jet1pt", "eta"],
        "add_jet1pt_phi": ["add_jet1pt", "phi"],
        "add_jet1pt_mass": ["add_jet1pt", "mass"],
        "add_jet1pt_Higgs1_deta": ["add_jet1pt", "LeadingHiggs_dEta"],
        "add_jet1pt_Higgs1_dphi": ["add_jet1pt", "LeadingHiggs_dPhi"],
        "add_jet1pt_Higgs1_m": ["add_jet1pt", "LeadingHiggs_mass"],
        "add_jet1pt_Higgs2_deta": ["add_jet1pt", "SubLeadingHiggs_dEta"],
        "add_jet1pt_Higgs2_dphi": ["add_jet1pt", "SubLeadingHiggs_dPhi"],
        "add_jet1pt_Higgs2_m": ["add_jet1pt", "SubLeadingHiggs_mass"],
        "sigma_over_higgs1_reco_mass": ["events", "sigma_over_higgs1_reco_mass"],
        "sigma_over_higgs2_reco_mass": ["events", "sigma_over_higgs2_reco_mass"],
    }
)

sig_bkg_dnn_PaddedArctanhDeltaProb_input_variables = OrderedDict(
    {
        # "year": ["events", "year"],
        "Padded_Arctanh_Delta_pairing_probabilities": [
            "events",
            "Padded_Arctanh_Delta_pairing_probabilities",
        ],
        "HT": ["events", "HT"],
        "hh_vec_mass": ["HH", "mass"],
        "hh_vec_pt": ["HH", "pt"],
        "hh_vec_eta": ["HH", "eta"],
        "hh_vec_phi": ["HH", "phi"],
        "hh_vec_DeltaPhi": ["HH", "dPhi"],
        "hh_vec_DeltaEta": ["HH", "dEta"],
        "hh_vec_DeltaR": ["HH", "dR"],
        "hh_CosThetaStar_CS": ["HH", "Costhetastar_CS"],
        "higgs1_reco_pt": ["HiggsLeading", "pt"],
        "higgs1_reco_eta": ["HiggsLeading", "eta"],
        "higgs1_reco_phi": ["HiggsLeading", "phi"],
        "higgs1_reco_mass": ["HiggsLeading", "mass"],
        "higgs2_reco_pt": ["HiggsSubLeading", "pt"],
        "higgs2_reco_eta": ["HiggsSubLeading", "eta"],
        "higgs2_reco_phi": ["HiggsSubLeading", "phi"],
        "higgs2_reco_mass": ["HiggsSubLeading", "mass"],
        "higgs1_DeltaPhijj": ["HiggsLeading", "dPhi"],
        "higgs2_DeltaPhijj": ["HiggsSubLeading", "dPhi"],
        "higgs1_DeltaEtajj": ["HiggsLeading", "dEta"],
        "higgs2_DeltaEtajj": ["HiggsSubLeading", "dEta"],
        "minDeltaR_Higgjj": ["events", "dR_min"],
        "maxDeltaR_Higgjj": ["events", "dR_max"],
        "higgs1_helicityCosTheta": ["HiggsLeading", "helicityCosTheta"],
        "higgs2_helicityCosTheta": ["HiggsSubLeading", "helicityCosTheta"],
        "higgs1_reco_jet1_pt": ["JetGoodFromHiggsOrdered:0", "pt"],
        "higgs1_reco_jet1_eta": ["JetGoodFromHiggsOrdered:0", "eta"],
        "higgs1_reco_jet1_phi": ["JetGoodFromHiggsOrdered:0", "phi"],
        "higgs1_reco_jet1_mass": ["JetGoodFromHiggsOrdered:0", "mass"],
        "higgs1_reco_jet2_pt": ["JetGoodFromHiggsOrdered:1", "pt"],
        "higgs1_reco_jet2_eta": ["JetGoodFromHiggsOrdered:1", "eta"],
        "higgs1_reco_jet2_phi": ["JetGoodFromHiggsOrdered:1", "phi"],
        "higgs1_reco_jet2_mass": ["JetGoodFromHiggsOrdered:1", "mass"],
        "higgs2_reco_jet1_pt": ["JetGoodFromHiggsOrdered:2", "pt"],
        "higgs2_reco_jet1_eta": ["JetGoodFromHiggsOrdered:2", "eta"],
        "higgs2_reco_jet1_phi": ["JetGoodFromHiggsOrdered:2", "phi"],
        "higgs2_reco_jet1_mass": ["JetGoodFromHiggsOrdered:2", "mass"],
        "higgs2_reco_jet2_pt": ["JetGoodFromHiggsOrdered:3", "pt"],
        "higgs2_reco_jet2_eta": ["JetGoodFromHiggsOrdered:3", "eta"],
        "higgs2_reco_jet2_phi": ["JetGoodFromHiggsOrdered:3", "phi"],
        "higgs2_reco_jet2_mass": ["JetGoodFromHiggsOrdered:3", "mass"],
        "add_jet1pt_pt": ["add_jet1pt", "pt"],
        "add_jet1pt_eta": ["add_jet1pt", "eta"],
        "add_jet1pt_phi": ["add_jet1pt", "phi"],
        "add_jet1pt_mass": ["add_jet1pt", "mass"],
        "add_jet1pt_Higgs1_deta": ["add_jet1pt", "LeadingHiggs_dEta"],
        "add_jet1pt_Higgs1_dphi": ["add_jet1pt", "LeadingHiggs_dPhi"],
        "add_jet1pt_Higgs1_m": ["add_jet1pt", "LeadingHiggs_mass"],
        "add_jet1pt_Higgs2_deta": ["add_jet1pt", "SubLeadingHiggs_dEta"],
        "add_jet1pt_Higgs2_dphi": ["add_jet1pt", "SubLeadingHiggs_dPhi"],
        "add_jet1pt_Higgs2_m": ["add_jet1pt", "SubLeadingHiggs_mass"],
        "sigma_over_higgs1_reco_mass": ["events", "sigma_over_higgs1_reco_mass"],
        "sigma_over_higgs2_reco_mass": ["events", "sigma_over_higgs2_reco_mass"],
    }
)

sig_bkg_dnn_BkgReweightingVariables_input_variables = OrderedDict(
    {
        "higgs1_reco_pt": ["HiggsLeading", "pt"],
        "higgs1_reco_eta": ["HiggsLeading", "eta"],
        "higgs1_reco_phi": ["HiggsLeading", "phi"],
        "higgs1_reco_mass": ["HiggsLeading", "mass"],
        "higgs2_reco_pt": ["HiggsSubLeading", "pt"],
        "higgs2_reco_eta": ["HiggsSubLeading", "eta"],
        "higgs2_reco_phi": ["HiggsSubLeading", "phi"],
        "higgs2_reco_mass": ["HiggsSubLeading", "mass"],
        "HT": ["events", "HT"],
        "higgs1_DeltaRjj": ["HiggsLeading", "dR"],
        "higgs2_DeltaRjj": ["HiggsSubLeading", "dR"],
        "minDeltaR_Higgjj": ["events", "dR_min"],
        "maxDeltaR_Higgjj": ["events", "dR_max"],
        "higgs1_helicityCosTheta": ["HiggsLeading", "helicityCosTheta"],
        "higgs2_helicityCosTheta": ["HiggsSubLeading", "helicityCosTheta"],
        "hh_CosThetaStar_CS": ["HH", "Costhetastar_CS"],
        "hh_vec_mass": ["HH", "mass"],
        "hh_vec_pt": ["HH", "pt"],
        "hh_vec_eta": ["HH", "eta"],
        "hh_vec_DeltaR": ["HH", "dR"],
        "hh_vec_DeltaPhi": ["HH", "dPhi"],
        "hh_vec_DeltaEta": ["HH", "dEta"],
        "higgs1_reco_jet1_pt": ["JetGoodFromHiggsOrdered:0", "pt"],
        "higgs1_reco_jet1_eta": ["JetGoodFromHiggsOrdered:0", "eta"],
        "higgs1_reco_jet1_phi": ["JetGoodFromHiggsOrdered:0", "phi"],
        "higgs1_reco_jet1_mass": ["JetGoodFromHiggsOrdered:0", "mass"],
        "higgs1_reco_jet2_pt": ["JetGoodFromHiggsOrdered:1", "pt"],
        "higgs1_reco_jet2_eta": ["JetGoodFromHiggsOrdered:1", "eta"],
        "higgs1_reco_jet2_phi": ["JetGoodFromHiggsOrdered:1", "phi"],
        "higgs1_reco_jet2_mass": ["JetGoodFromHiggsOrdered:1", "mass"],
        "higgs2_reco_jet1_pt": ["JetGoodFromHiggsOrdered:2", "pt"],
        "higgs2_reco_jet1_eta": ["JetGoodFromHiggsOrdered:2", "eta"],
        "higgs2_reco_jet1_phi": ["JetGoodFromHiggsOrdered:2", "phi"],
        "higgs2_reco_jet1_mass": ["JetGoodFromHiggsOrdered:2", "mass"],
        "higgs2_reco_jet2_pt": ["JetGoodFromHiggsOrdered:3", "pt"],
        "higgs2_reco_jet2_eta": ["JetGoodFromHiggsOrdered:3", "eta"],
        "higgs2_reco_jet2_phi": ["JetGoodFromHiggsOrdered:3", "phi"],
        "higgs2_reco_jet2_mass": ["JetGoodFromHiggsOrdered:3", "mass"],
        "add_jet1pt_pt": ["add_jet1pt", "pt"],
        "add_jet1pt_eta": ["add_jet1pt", "eta"],
        "add_jet1pt_phi": ["add_jet1pt", "phi"],
        "add_jet1pt_mass": ["add_jet1pt", "mass"],
        "sigma_over_higgs1_reco_mass": ["events", "sigma_over_higgs1_reco_mass"],
        "sigma_over_higgs2_reco_mass": ["events", "sigma_over_higgs2_reco_mass"],
    }
)


if __name__ == "__main__":
    # print the difference between the two dictionaries
    def print_dict_diff(dict1, dict2):
        for key in dict1:
            if key not in dict2:
                print(f"Key {key} is missing in the second dictionary")
            elif dict1[key] != dict2[key]:
                print(f"Key {key} has different values: {dict1[key]} vs {dict2[key]}")
        for key in dict2:
            if key not in dict1:
                print(f"Key {key} is missing in the first dictionary")

    # Call the function to print the differences
    print(
        "Differences between bkg_morphing_dnn_input_variables and bkg_morphing_dnn_input_variables_altOrder:"
    )
    print_dict_diff(bkg_morphing_dnn_input_variables, sig_bkg_dnn_input_variables)
